SasView/sasview

- src/sas/sascalc/dataloader/readers/cansas_reader.py
- src/sas/sasgui/guiframe/local_perspectives/data_loader/data_loader.py
The cansas data loader is not handling errors correctly. There are two parts to this fix:
1- If the cansas file is invalid, the loader should raise an exception. At the moment it's returning an invalid object (a list containing an error string rather than a data object with an error data member). It should simply raise an exception that will be properly logged.
2- In the event that a loader returns an invalid object, the UI object handling should still behave properly.
> Improve loading error handling

- src/sas/sascalc/dataloader/manipulations.py
- src/sas/sasgui/guiframe/local_perspectives/plotting/Plotter2D.py
For some reason, the box slicers, box sum, annular averaging and sector averaging routines need data2d objects with one and only one detector given within the data set. I'm curious to know the reason behind this. This fix allows data sets with no detector information to use the slicers, sum and averaging.
> Ticket 824

- src/sas/sasgui/perspectives/pr/media/pr_help.rst
The real change is a transpose typo in the year 1908 -> 1980.  My editor also removed trailing whitespace (not a conscious change).  If you want me to revert those changes I can but it's pretty clear they were innocuous so maybe they are fine.
> this fixes a transpose typo in the year

- src/sas/sascalc/calculator/slit_length_calculator.py
This code was using float indexing which prevents recent numpy versions from working.
> MAINT: SlitlengthCalculator - removed float indexing

- sasview/local_config.py
- src/sas/sasgui/guiframe/acknowledgebox.py
- src/sas/sasgui/guiframe/config.py
Changed:
- control used to display text so that users can copy/paste and so it autosizes
- order of elements to be a bit more logical
Needs testing on windows before merge.
Required for 4.1 (in previous versions, the citation and acknowledgment was truncated)
Expected layout (from mac) is:
> Fixing acknowledgements box

- test/corfunc/test/utest_corfunc.py
Removes an unused matplotlib import in `utest_corfunc`.
> MAINT: remove unused matplotlib import

- src/sas/sascalc/dataloader/manipulations.py
- src/sas/sascalc/dataloader/readers/IgorReader.py
- test/sasdataloader/test/utest_abs_reader.py
`IgorReader` was failing in recent versions of numpy because it was using float instead of int for indexing. This PR fixes this issue, outlined in 888.
The PR adds a smoke test to ensure that `IgorReader` can load the Igor file without complaining.
Note: it's not clear to me where in the Loader hierarchy files are closed. e.g. in `IgorReader.read` a file is opened, but it's never actually closed.
> BUG: IgorReader

- check_packages.py
Modified check_packages.py to work with python 3 as well. It checks for the major python version and warns that py2 is required for the GUI (not sure if py2 is required for any other mode of operation).
Several PEP8 fixes have been applied.
> MAINT: check_packages.py should work in py3

- src/sas/sascalc/dataloader/data_info.py
- src/sas/sascalc/dataloader/readers/cansas_constants.py
- src/sas/sascalc/dataloader/readers/cansas_reader.py
To eventually accomodate non-isotropic samples, SESANS needs a yacceptance variable to go with the zacceptance one.
> Add yacceptance

- src/sas/sasgui/perspectives/fitting/fitpage.py
- src/sas/sasgui/perspectives/fitting/models.py
There was an awkward bug where, if a plugin model was modified (so that the .py and the .pyc were out of sync), it would cause an error message until the user reloaded the models.
> Improve model reloading bug

- src/sas/sasgui/perspectives/calculator/sld_panel.py
To make the SLD calculator more useful for x-ray users, inputs in the form of energies, source elements or wavelengths are now accepted instead of displaying the x-ray SLD at two fixed energies.
> SLD Calculator Modifications

- test/sasdataloader/test/utest_abs_reader.py
This PR ensures that the specific reader works for each type of file. Previously all the reading was being done by `Loader`, which would direct the file towards the specific reader. If the specific reader was failing (which was seen recently), then another reader would be tried. The read with the alternate reader would fail, indicating that it was the alternate readers fault. Here the specific reader is checked, it also checks that `Loader` directs the file towards the correct specific reader.
> TST: ensure specific readers work

- src/sas/sasgui/perspectives/fitting/models.py
Some minor tidying of the _findModels function.  The main concern was the `dir` parameter on the function call, which
a) was never used
b) shadowed the dir builtin, making the function harder to debug
> Find models tidy

- src/sas/sasgui/perspectives/fitting/basepage.py
- src/sas/sasgui/perspectives/fitting/fitpage.py
- src/sas/sasgui/perspectives/fitting/fitting.py
- src/sas/sasgui/perspectives/fitting/models.py
Allows users to define structure factor models by adding `structure_factor = True` to an 'advanced' custom model.py file. Similarly, form factor models can be defined by adding `form_factor = True`
Fixes ticket [#861](http://trac.sasview.org/ticket/861)
> Ticket 861

- src/sas/sascalc/dataloader/file_reader_base_class.py
- src/sas/sascalc/dataloader/readers/cansas_reader.py
- src/sas/sascalc/dataloader/readers/cansas_reader_HDF5.py
- test/sasdataloader/test/utest_abs_reader.py
- test/sasdataloader/test/utest_ascii.py
- test/sasdataloader/test/utest_averaging.py
- test/sasdataloader/test/utest_generic_file_reader_class.py
- test/sasdataloader/test/utest_red2d_reader.py
- test/sasdataloader/test/utest_sesans.py
I added a reset_state class variable to the FileReader class that empties class variable output every time a new read is initiated. I also added unit tests to be sure the proper number of data sets are being returned from each reader. This should resolve issue [1013](http://trac.sasview.org/ticket/1013).
> Ticket 1013 - Reset FileReader class state on every data load

- setup.py
The current entry point defined by `setup.py` has not caught up with the change to the function name for the entry point:
```
$ sasview
Traceback (most recent call last):
File "/usr/bin/sasview", line 11, in <module>
load_entry_point('sasview==4.2.0', 'console_scripts', 'sasview')()
File "…/lib/python2.7/site-packages/pkg_resources/__init__.py", line 564, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File …/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2662, in load_entry_point
return ep.load()
File …/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2316, in load
return self.resolve()
File "…/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2326, in resolve
raise ImportError(str(exc))
ImportError: 'module' object has …
```
> Fix entry point to point to new run_gui function

- test/fileconverter/test/utest_nxcansas_writer.py
`pylint` is unused so there's no need to have it installed to be able to run these tests.
> Remove unused pylint import in test

- docs/sphinx-docs/source/_extensions/dollarmath.py
The new orientation docs use ```$x$-$y$-$z$```, etc., instead of ```$x$\ -\ $y$\ -\ $z$```, so the sasmodels docs that are included in sasview will not render correctly without this patch.
> consistent $-math expression for sasmodels and sasview, now allowing 1-$\sigma$

- src/sas/sascalc/dataloader/file_reader_base_class.py
Class variables get inherited and shared between different instantiations
of the class and this means that the current usage of `TestFileReader` in
`utest_generic_file_reader_class.py` has side-effects that would cause
subsequent tests to fail.
(See an upcoming PR for why being able to run lots of tests at once is useful)
> Fix instance vs class variables in FileReader

- pytest.ini
- src/sas/sascalc/dataloader/file_reader_base_class.py
- test/corfunc/test/utest_corfunc.py
- test/fileconverter/test/utest_nxcansas_writer.py
- test/pr_inversion/test/utest_explorer.py
- test/pr_inversion/test/utest_invertor.py
- test/sascalculator/test/utest_sas_gen.py
- test/sascalculator/test/utest_slit_length_calculator.py
- test/sasdataloader/test/utest_abs_reader.py
- test/sasdataloader/test/utest_ascii.py
- test/sasdataloader/test/utest_averaging.py
- test/sasdataloader/test/utest_cansas.py
- test/sasdataloader/test/utest_extension_registry.py
- test/sasdataloader/test/utest_generic_file_reader_class.py
- test/sasdataloader/test/utest_red2d_reader.py
- test/sasdataloader/test/utest_sesans.py
- test/sasguiframe/test/utest_manipulations.py
- test/sasinvariant/test/utest_data_handling.py
- test/sasinvariant/test/utest_use_cases.py
Test resources are in the same directory (or a child directory) of the test code, so the code can locate the resources itself rather than relying on the tests being run from a certain location. This PR adds a trivial function to find the necessary data files for the tests.
Making the tests more robust to the current working directory allows the tests to be used against installed code rather than the current checkout. These changes also allow automated test discovery to work and so tools like `py.test` can run all (or a selection of) tests at once, without the need for a custom test runner script; a `pytest.ini` configuration is included to facilitate this. For example, in the Debian packaging, we can now run the tests against the compiled version by running nothing more than `py.test`. …
> Make tests work from any directory and functional without special runner script

- src/sas/sasgui/perspectives/fitting/gpu_options.py
On Linux, if there is no OpenCL driver, then PyOpenCL will load properly, but then throw a logic error when attempting to enumerate the platforms.  This patch catches that exception and allows sasview to continue on without pyopencl.
> ticket-995 OpenCL required on Linux even if turned off in GUI

- src/sas/sasgui/perspectives/fitting/basepage.py
sasmodels contains filenames that are not all lowercase ([unified_power_Rg.py](https://github.com/SasView/sasmodels/blob/master/sasmodels/models/unified_power_Rg.py)) and so the HTML help pages generated for this model are also mixed case (unified_power_Rg.html). The current code forces the filename for the HTML help file to lowercase means that the help for this model will not be found.
```
2018-01-09 09:38:41,256 : INFO : root (kernelpy.py:36) :: load python model unified_power_Rg
2018-01-09 09:38:44,161 : ERROR : sas.sasgui.guiframe.documentation_window (documentation_window.py:102) :: Could not find Sphinx documentation at /usr/lib/python2.7/dist-packages/sas/sasview/doc/user/models/unified_power_rg.html -- has it been built?
```
```
$ ls -l …
```
> Allow models to have mixed case filenames in help

- docs/sphinx-docs/source/conf.py
mathrm only works in math mode, but we want to be able to use the
angstrom symbol everywhere
> Take Angsgtrom symbol out of mathrm

- src/sas/sasgui/perspectives/fitting/basepage.py
This PR fixes the issue with loading projects saved using the Uniform distribution introduced in the boltzmann sasmodels branch. The project loader was using the index of the distribution combobox to check for a distribution array. The Uniform distribution was put into the position the Array distribution used to hold causing the issue seen in [ticket 1018](http://trac.sasview.org/ticket/1018#comment:5).
This PR is tied to [sasmodels PR59](https://github.com/SasView/sasmodels/pull/59).
> Fix loading of projects with the Uniform distribution

- src/sas/sascalc/fit/models.py
- src/sas/sasgui/perspectives/calculator/model_editor.py
I created a new environment variable PLUGIN_MODEL_DIR set in sasview and used in sasmodels to find the plugin directory. As a bonus, the Sum|Multi window model combo boxes are updated when a new plugin model is created.
This depends on [sasmodels PR 63](https://github.com/SasView/sasmodels/pull/63).
> Ticket 1052: Allow custom models to be used in sum|multi models

- src/sas/sasgui/perspectives/fitting/fitpage.py
- src/sas/sasgui/perspectives/fitting/media/fitting_help.rst
- src/sas/sasgui/perspectives/fitting/media/residuals_help.rst
Besides updating the documentation in residual_help which was already close and that in fitting_help which was less so, the section on simultaneous fitting was also updated since it referred to chi^2.
closes #930
> Ticket 930 chi squared documentation updating to clarify we use reduced chi2

- test/sascalculator/test/utest_sas_gen.py
A newly added test missed the call to `find()`, breaking the use of pytest.
(Would you be open to using pytest to run the tests on travis? Is there any functionality that `utest_sasview.py` provides that a simple call to pytest doesn't? Example of this failure being caught on travis at https://travis-ci.org/llimeht/sasview/jobs/351702734 )
> Fix finding of test resource

- build_tools/requirements.txt
- setup.py
matplotlib has a minimum version of pyparsing ("Matplotlib requires pyparsing>=2.0.1;") that is considerably greater than and also incompatible with the 1.5.5 that pyparsing is currently pinned to. Travis currently installs 1.5.5 and 1.5.7 and 2.2.0 within the system via apt, conda and pip. 
This patch fixes up the sasview requirement so that matplotlib and sasview are co-installable, possibly addressing the pyparsing issues described in #143.
(As a general rule, avoiding `==` dependencies is really important for maintaining the ability to install the required packages. Use of `>=` to ensure a particular feature is available or a particular bug is fixed is best. Most maintainers are of dependencies will work to ensure that API compatibility is maintained, at least across minor and micro …
> Drop incorrect version req on pyparsing

- src/sas/sascalc/fit/pagestate.py
- src/sas/sasgui/guiframe/report_dialog.py
- src/sas/sasgui/perspectives/fitting/basepage.py
Simply disabling saving functionality for OSX due to issues with generating empty pdf files.
> Removing save button from OSX

- src/sas/sasgui/perspectives/fitting/basepage.py
This fixes an issue that was found when the new distribution functions were introduced, but was present for all distributions, just not seen until now. The method _check_value_enter in basepage.py is where GUI changes are sent to the model. When any dispersity parameter was updated, a boolean check that also updates the model for all parameter types, would end prematurely, never reaching the model and orientation parameters. Having NaN in any dispersity parameter would make this boolean true and the uniform distribution defaults to NaN for nsigmas, exposing this issue.
> Ticket #1081 - Polydispersity parameter changes stop other model changes

- src/sas/sasgui/perspectives/calculator/resolution_calculator_panel.py
The wx backend no longer eposes both NavigationToolbar2WxAgg and
NavigationToolbar2Wx. Since the resolution calculator still used the Wx
name not the WxAgg name, it could not be imported, and neither could any
of sas.sasgui.perspectives.fitting. The ImportError in the SasView constructor
(sas/sasview/sasview.py:67, import sas.sasgui.perspectives.fitting fails)
leaves the GUI pretty messy and fitting is not possible.
> Fix imports for matplotlib 2.2.2

- test/corfunc/test/utest_corfunc.py
`transform_isrunning()` returns `False` both before the calculation has started and also after the calculation has finished. The test of the transformation was only considering the latter case and so was regularly failing on the reproducible-builds.org test infrastructure. (This patch has been in place for a couple of months without failure.)
There is, perhaps, a broader discussion about whether the `transform_isrunning()` should return `False` when the calculation is yet to start (`complete` or `completed` would be a better test), but I don't know the wider implications of that suggestion throughout the code.
> Fix race condition in test

- src/sas/sasgui/perspectives/fitting/basepage.py
- src/sas/sasgui/perspectives/fitting/fitpage.py
This fixes the issue with the orphaned error boxes that show up on the top-left of the fit page when first assigning data (not in the ticket) as well as when the polydispersity distribution is changed. Also, I made the error value read-only. They appear similar to other values, but cannot be edited now.
> Ticket 1069: Fix for orphaned error boxes

- src/sas/logger_config.py
- src/sas/logging.ini
- src/sas/qtgui/MainWindow/GuiManager.py
- src/sas/qtgui/MainWindow/MainWindow.py
- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
- src/sas/qtgui/Utilities/LocalConfig.py
- src/sas/qtgui/Utilities/SasviewLogger.py
- src/sas/qtgui/Utilities/UnitTesting/SasviewLoggerTest.py
In summary:
* disable generic stdout/stderr redirection to Log Explorer, to make program output more permanent in the event of a crash
* all logs are still propagated to the Log Explorer, console, and log file (with separate handlers)
* minor fixes (Log Explorer auto-scroll, log levels no longer changing in different places)
for JIRA users, please see: <https://jira.esss.lu.se/browse/SASVIEW-957>
for trac users, please see: <http://trac.sasview.org/ticket/1123>
> SASVIEW-957 logging changes

- src/sas/qtgui/Perspectives/Fitting/FittingUtilities.py
- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
Fixes for:
- [SASVIEW-960](https://jira.esss.lu.se/browse/SASVIEW-960) &ndash; Cannot fit any S(Q) params if using P(Q)S(Q) model
- [SASVIEW-971](https://jira.esss.lu.se/browse/SASVIEW-971) &ndash; Constraining an S(Q) param to its current value crashes the app
Beforehand, only the `model_info` structures were being updated when the user selected a S(Q); without updating the `kernel_module` object (which is really a `SasviewModel` object), the application could not access the S(Q) parameters for fitting or constraints.
----
Additionally, any parameters in the table which are not found in the kernel module's parameter list (i.e. they cannot be currently fitted &ndash; this is exclusively `radius_effective`, at the moment) are now greyed-out in the table, and cannot be checked, selected or …
> SASVIEW-971: Constraining an S(Q) param to its current value crashes the app

- src/sas/sascalc/dataloader/readers/abs_reader.py
- test/sasdataloader/test/utest_abs_reader.py
Igor analysis uses the Q_mean from ABS files when analyzing the data. The Q_mean diverges from Q closer to the beam stop as outlined in a paper by John Barker. This is related to the issue in [ticket 1102](http://trac.sasview.org/ticket/1102).
> Use Q_mean from ABS files to match Igor analysis

- src/sas/sasgui/guiframe/local_perspectives/plotting/parameters_panel_slicer.py
- src/sas/sasgui/guiframe/media/graph_help.rst
Documentation for batch slicing added in 4.2b. A help button was added to the slicer parameters window that should link to the 2D data averaging section, but anchors are currently broken as outlined in [Trac ticket 1104](http://trac.sasview.org/ticket/1104).
> Batch slicer documentation - 1139

- src/sas/sascalc/fit/pagestate.py
Saved projects hold the SasView version number in them for backward compatibility checks. The version is  put into a tuple of integers as (major, minor, point) e.g. (4, 1, 2). Adding '-beta' caused the int conversion to fail. This fix removes all non numeric characters from the version number when loading the project.
If desired, I can also remove the non-numeric characters when saving projects, but that isn't included in this PR as of yet.
> Beta Load Project Issue Fix

- src/sas/sasgui/perspectives/calculator/pyconsole.py
Hide the module reload problem that was breaking the plugin editor tests for pure python models with global references.
We could do better by refactoring the sasview model interface.  See comments in code for details.
> Ticket 1142 plugin reload

- src/sas/sasgui/perspectives/calculator/slit_length_calculator_panel.py
As of 4.2-beta, all data loaded into SasView is returned as a list to allow for any number of data sets to be loaded simultaneously. The calculator perspective expected a Data1D object instead of a list, causing the issue outlined in [ticket 1132](http://trac.sasview.org/ticket/1132).
> Load data for slit size calculator - 1132

- installers/setup_exe.py
- src/sas/sasgui/perspectives/fitting/gpu_options.py
Added dependency on pkg_resources to setup_exe.py in order for pyopencl to find the correct path to the include directory.
> Added dependency required for pyopencl on win64 - ticket 1131

- src/sas/sasgui/perspectives/calculator/media/slit_calculator_help.rst
- src/sas/sasgui/perspectives/calculator/model_editor.py
Fixes the help string for sum model as per ticket #1163.  Also attempted to fix problem with lack of superscript on TM in the slit calculator which was not formatted correctly.  It is now formatted correctly as demonstrated with online sphinx markup editor however my build system does not seem to handle it.  I will try a PR build to see if it is our sphinx setup or my system.
Also note that it seems that substitution is not working for this sphinx build.
> Ticket 1163 plus come docs

- .gitignore
- docs/sphinx-docs/build_sphinx.py
- docs/sphinx-docs/source/conf.py
- docs/sphinx-docs/source/rst_prolog
- src/sas/sasgui/perspectives/calculator/media/slit_calculator_help.rst
Fix the problem with sphinx superscript and substitution (Ticket [1164](http://trac.sasview.org/ticket/1164)) in an emphasized environment by removing the emphasis.
Not the best solution.  May want to try the most recent version of sphinx under python 3 to see if this problem has already been fixed upstream.  
Other option is to turn off emphasis for the superscript and the substitution.
> Ticket 1164 slit calculator docs

- src/sas/qtgui/Perspectives/Fitting/FittingUtilities.py
- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
- src/sas/qtgui/Perspectives/Fitting/UnitTesting/FittingWidgetTest.py
These changes update the main param table:
- Subheadings for P(Q) and S(Q) are added to make the origin of each parameter clear
- radius_effective is no longer shown (if using sasmodels master) because it is not manipulable yet
- Duplicate parameter names from different models (i.e. if P(Q) and S(Q) each have a parameter with the same name) are no longer displayed with the conjured suffix '_S' (the subheadings make it clear which is which)
> SASVIEW-966: Organise parameter table by model component

- src/sas/qtgui/Perspectives/Fitting/AssociatedComboBox.py
- src/sas/qtgui/Perspectives/Fitting/FittingUtilities.py
- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
This introduces support for fixed-choice parameters in models (including structure factors).
There are currently no built-in models (to my knowledge) that attempt to include fixed-choice parameters, but sasmodels contains the functionality.
This does not include support for parameters added to product models by sasmodels (see SASVIEW-1034); this will be introduced in a subsequent patch, bringing us very close to beta approximation support.
> SASVIEW-1032: Support for fixed-choice model parameters, e.g structure_factor_mode

- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
In sasmodels dev branches, sasmodels' product.py will inject parameters into the product model that are not a part of either P(Q) nor S(Q), e.g. structure_factor_mode, radius_effective_mode.
These parameters are placed in the parameter table above the P(Q)- and S(Q)-specific parameters and headings.
> SASVIEW-1034: Support for parameters injected into the product model by sasmodels

- src/sas/qtgui/Perspectives/Fitting/FittingLogic.py
- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
- src/sas/qtgui/Perspectives/Fitting/ModelThread.py
- src/sas/qtgui/Perspectives/Fitting/UnitTesting/FittingLogicTest.py
This sasmodels feature is implemented in the branch beta_approx and (I assume) is relatively stable; SasViewModel._intermediate_results is a callable which, when called, returns a dict of intermediate results, keyed by name.
Support is retained for sasmodels master, whereby P(Q) and S(Q) data are specifically returned directly.
Note the conflict with PR #169 (easy to resolve but notable)
> SASVIEW-1033: Support for sasmodels' new 'lazy' intermediate results

- src/sas/sasgui/guiframe/gui_manager.py
Have changed the action of Help >> Tutorial (which used to just bring up Tutorial.pdf - the old tutorial) to Help >> Tutorials, which now redirects to /doc/user/tutorial.html and gives access to all the tutorials. Addresses #1175. I have left the original code in place but commented out.
> Redirect Help >> Tutorial to Documentation tutorials page

- src/sas/qtgui/Perspectives/Fitting/FittingLogic.py
- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
([See JIRA issue](https://jira.esss.lu.se/browse/SASVIEW-1052).)
The radius_effective_mode functionality was merged into sasmodels' beta_approx branch, so it is as stable as the rest of the beta approximation-related features which I have already merged into ESS_GUI. Therefore this should be merged in too.
In summary, the value of radius_effective_mode is checked, and the radius_effective parameter is made editable/non-editable appropriately. Additionally, when a model has been evaluated and radius_effective has been calculated in the model and passed back as an intermediate result, it is placed into the parameter table so the user can view it.
> SASVIEW-1052: Let user choose if radius_effective is computed from form factor, or free/fittable

- src/sas/sascalc/fit/pagestate.py
- src/sas/sasgui/perspectives/invariant/invariant_state.py
The SasView version number is added to the title bar in Fit and Invariant reports. This handles ticket 1179 for v4.2, but I can't speak for v5.0 and beyond.
> Ticket 1179: Add the SasView version to Report Files

- src/sas/sasgui/perspectives/fitting/basepage.py
Set magnetic defaults in units of `1e-6/Ang^2`.
This does not address the main part of the ticket, which is that the magnetic values reset to the default when magnetism is toggled off and on.
> Ticket 1004: remove e-06 from default magnetism values.

- run.py
- setup.py
- src/sas/sascalc/calculator/c_extensions/__init__.py
- src/sas/sascalc/calculator/c_extensions/sld2i_module.c
- src/sas/sascalc/calculator/sas_gen.py
- src/sas/sascalc/file_converter/bsl_loader.py
- src/sas/sascalc/file_converter/c_ext/__init__.py
- src/sas/sascalc/file_converter/c_ext/bsl_loader.c
- src/sas/sascalc/pr/c_extensions/Cinvertor.c
- src/sas/sascalc/pr/c_extensions/__init__.py
- src/sas/sascalc/pr/fit/BumpsFitting.py
- src/sas/sascalc/pr/fit/Loader.py
- src/sas/sascalc/pr/invertor.py
- src/sas/sascalc/pr/num_term.py
Move c extensions from core/module.so to _module.so.  This allows an inplace build of the C models so that run.py doesn't need to do tricks to load the module from the build path while the rest of the package is loaded from the src path.
Also included is some cleanup for improved python 3 support.
> simplify C build

- src/sas/sasgui/perspectives/fitting/fitting.py
Fixes the problem with data weights set in the GUI being ignored in the fit.
Note that the bug was introduced while fix something to do with 2D plotting.  With this fix, a quick test doesn't show any problem.  Tried with 1D and 2D calculations, with and without data, and with 1D and 2D fits.  Maybe this change was put in to fix a more subtle bug?
> Ticket 1205: use data weights from the GUI in the fit

- src/sas/sasgui/perspectives/fitting/fitpage.py
All changes are to fitpage.py.  Changed behavior so that both 1D and 2D smearing from data are shown as dq/q in % and changed several labels to more clearly indicate what is being displayed.  2D smearing had some serious logic problems (for example when using dq from data both boxes come up but showed "NONE" while for custom pinhole the same two boxes show up (non editable) even though only one input is allowed.  Finally issues with switching from 2D to 1D displayed options for smearing even if there was not model to smear. 
Also added a bunch of logging statements
Since some (not insignificant in this convoluted module) logic had to be changed the code should be checked carefully as well as tested. 
Addresses #1206
Addresses #1222
> Ticket 1206 - fix problems in smearing sizer

- src/sas/sascalc/corfunc/transform_thread.py
- src/sas/sasgui/perspectives/corfunc/corfunc_panel.py
This upgrades the default corfunc range from 200 to 1000.  For version 5, we should make this into a controlable parameter, but this will be enough for 4.2.1
> Ticket 1223: Expand permitted range of transformed data in Corfunc implementation

- .gitignore
- conftest.py
Note: based off of simplify-c-build, which already contains mods to allow `python setup.py test`.
The .eggs directory is created during the test to pull in pytest helpers.  Without an internet connection, need to use `pip install pytest_runner`, which should perhaps be added to the requirements files and yaml files for setting up conda environments.
> support pytest

- setup.py
Removing code that removes local .sasview directory. It seems to have no effect on building installers but it may require some edge case testing.
> Ticket #1219: cleaning up setup

- setup.py
Dear developers,
I attempted to install this package at NSLS-II, and had some problems with executing it once it's installed. This PR attempts to resolve the entry point, so that one does not have to run `python run.py`. Instead, simple calling of `sasview` will pop up the GUI window. The PR is based on the [v5.0-beta.2](https://github.com/SasView/sasview/releases/tag/v5.0-beta.2) tag.
I hope it will help to make the package easier to use. Our plan is to create a corresponding conda package in our channel https://anaconda.org/lightsource2-tag based on the updated installer. Please let me know if there is an interest in contribution.
Regards,
Maksim Rakitin
DAMA group, NSLS-II, BNL
> FIX: add a proper entry point

- src/sas/sascalc/fit/expression.py
Jenkins is showing the following error:
```
Traceback (most recent call last):
File "setup_mac.py", line 61, in <module>
from sas.sasgui.perspectives import fitting
File "/Users/sasview/Jenkins/workspace/SasView_OSX10.10/sasview/sasview-install/sasview-4.2.1-py2.7-macosx-10.10-intel.egg/sas/sasgui/perspectives/fitting/__init__.py", line 3, in <module>
from fitting import *
File "/Users/sasview/Jenkins/workspace/SasView_OSX10.10/sasview/sasview-install/sasview-4.2.1-py2.7-macosx-10.10-intel.egg/sas/sasgui/perspectives/fitting/fitting.py", line 34, in <module>
from sas.sascalc.fit.BumpsFitting import BumpsFit as Fit
File "/Users/sasview/Jenkins/workspace/SasView_OSX10.10/sasview/sasview-install/sasview-4.2.1-py2.7-macosx-10.10-intel.egg/sas/sascalc/fit/BumpsFitting.py", line 33, in <module> …
```
> fix doc build error on jenkins mac

- src/sas/qtgui/Calculators/SldPanel.py
- src/sas/qtgui/Calculators/UI/SldPanel.ui
I've separated the neutron and Xray sld calculation so that there's no possibility of cross talk, which was present in the original bus report.  This also makes it possible for the user to continue working with JUST an Xray or Neutron wavelength, without needing to supply both.
Also, as mentioned in the task, I've made the EditText boxes enabled but readOnly, which allows the user to copy the values out of the boxes (which wasn't previously possible).  It's also a bit easier to read the text boxes when they aren't disabled.
> Sasview 1142

- src/sas/qtgui/Perspectives/Corfunc/CorfuncPerspective.py
- src/sas/qtgui/Perspectives/Corfunc/UI/CorfuncPanel.ui
- src/sas/sascalc/corfunc/transform_thread.py
I've fixed the Corfunc perspective so that both the Q-Space extrapolation and the real space transform are both plotted.  Additionally, the plots are now included alongside the dialog on the right, instead of being squeezed in at the top, which make the plots easier to read.  Finally, I've added axes labels to the plots for additional clarity.
Ignore to odd colour scheme in the imags below.  That's a known issue with my computer alone.
Before
After
> Sasview 1079

- src/sas/sasgui/perspectives/fitting/fitpage.py
Custom pinhole smearing should use dQ/|Q| rather than dQ/Q [http://trac.sasview.org/ticket/1242](Ticket #1268).
> Use dQ/|Q| for 2-D resolution

- src/sas/qtgui/Plotting/Plotter.py
- src/sas/qtgui/Plotting/UnitTesting/PlotterTest.py
In the 5.0 GUI, SESANS data is correctly flagged that it should be plotted on a linear scale, instead of a log scale.  However, on a different abstraction level, the data is transformed to remove all of the negative values to prepare for log plotting.  Since SESANS data is always negative, this results with nothing being plotted.  There was an existing workaround of switch to log scale and then back to a linear scale, but this patch plots the data correctly on first load.
I've also modified the unit tests to catch any regressions.
> SasView Jira 1293

- src/sas/qtgui/Perspectives/Fitting/FittingLogic.py
- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
Refs #1280, #1295, sasview/sasmodels#219, sasview/sasmodels#199, sasview/sasmodels#101.
Removes confusion when volfraction appears in both S and P models.  No longer supports volfraction renamed to volfraction_S or any other name collisions.   
This is a short-term fix.  Longer term address #1190, #1194 and sasview/sasmodels#231 to better decouple the GUI and the sasmodels library.
> Only show volfraction once if it appears in both P and S models.

- src/sas/sasgui/perspectives/file_converter/converter_widgets.py
Fixes small bug in setting file metadata for the file converter widget.  
AddSpacer interface changed between wxpython 3 and 4.
Tested against wx 3: `conda install -c travis wxpython`
```
11:20:02 - INFO : sas.sasview.sasview: 198: Python: 2.7.16 |Anaconda, Inc.| (default, Aug 22 2019, 10:59:10) 
11:20:03 - INFO : sas.sasview.sasview: 228: Wx version: 3.0.0.0
11:20:03 - INFO : sas.sasview.sasview: 229: Wx PlatformInfo: ('__WXMAC__', 'wxMac', 'unicode', 'wxOSX', 'wxOSX-cocoa', 'wx-assertions-on', 'SWIG-1.3.29')
```
and wx 4: `conda install wxpython`
```
11:20:58 - INFO : sas.sasview.sasview: 198: Python: 3.7.0 (default, Jun 28 2018, 07:39:16) 
11:20:58 - INFO : sas.sasview.sasview: 228: Wx version: 4.0.4
11:20:58 - INFO : sas.sasview.sasview: 229: Wx PlatformInfo: ('__WXMAC__', 'wxMac', …
```
> wx4 bug in fileconverter: AddSpacer interface is changed

- src/sas/sascalc/simulation/setup.py
The incorrect path leads to install errors when building binary packages.
> Fix path to sascalc simulations in setup.py

- docs/sphinx-docs/source/user/RELEASE.rst
sphinx running under Python 3 can't build the documentation with mixed encoding in the changelog.
> Fix wrongly encoded quotes in changelog

- src/sas/sascalc/pr/p_invertor.py
The OS/X build on Jenkins is failing because it has an old version of numpy.  This fixes the code so that old numpy will continue to work, and let the tests pass again.
> fix pr bug for older numpy: x[True] did not select all elements

- setup.py
`setup.py` will build the sasmodels documentation if it is not present. The documentation build should be performed with the same interpreter as `setup.py` is using. If the interpreter is not specified when calling `make`, then the path will be searched for an executable called `python`; this can mean accidentally switching from Python 3 to Python 2, with required tools like sphinx perhaps not being available for that interpreter.
> Use same interpretor to build sasmodels

- src/sas/sascalc/dataloader/file_reader_base_class.py
- src/sas/sascalc/dataloader/readers/red2d_reader.py
The 2D data format from the VSANS instrument at the NCNR is now outputting a mask flag for each data point. This should read in the mask and format it so SasView can use it.
NB - I have no data sets with the mask column to test. The latest release of the Igor Macros (v7.93 - June 12, 2019) adds the mask data to the reduced data file. This PR may (should?) never get merged into master because we are actively working on writing VSANS data in NXcanSAS, which may supercede the .DAT format.
> Load in Mask Data column from NCNR 2D data.

- src/sas/qtgui/MainWindow/UI/TabbedFileLoadUI.ui
`TabbedFileLoadUI.ui` refers to the resources file which then causes an `import main resources_rc` statement to be added to the bottom of the corresponding `TabbedFileLoadUI.py`. 
sphinx then dislikes this import:
> WARNING: autodoc: failed to import module 'TabbedFileLoadUI' from module 'sas.qtgui.MainWindow.UI'; the following exception was raised:
> No module named 'main_resources_rc'
(While this is currently only a warning, it does prevent apidocs being generated for that file; the documentation build needs to become free of warnings so that CI can be made to gate on the build passing. See #1399)
I've not been able to figure out whether it's the use of relative paths in the include or some other issue. Simply stopping `TabbedFileLoadUI.ui` from referring to the qrc file seems to be …
> Drop qrc file from .ui to permit doc building

- build_tools/conda_qt5_min_ubuntu.yml
Due to issue with pyinstaller we need to downgrade setuptools. 
https://github.com/pypa/setuptools/issues/1963
Testing if this works on build system. Don't review!
> setuptools downgraded to 0.45

- docs/sphinx-docs/source/conf.py
Mock-out Qt imports from the autodoc calls so that Qt is not imported; importing Qt adds lots of noise to the docs and also requires a display to be available.
> Skip Qt imports when building docs

- src/sas/qtgui/Perspectives/Inversion/InversionLogic.py
This is a fix for #1462. The P(r) plot now defaults to linear x and y axes.
> Ticket 1462: Default to linear axes for P(r) plot

- setup.py
Calling "setup.py clean" should remove generated files and be fast, rather than creating lots of files and be slow. This patch at least stops "setup.py clean" from building the Qt GUI, although it doesn't clean up the generated files.
This is a bit of a crude hack; it's better than the current situation but far from perfect.
> Don't build Qt GUI when setup.py is asked to clean

- src/sas/qtgui/MainWindow/DataExplorer.py
- src/sas/sascalc/dataloader/file_reader_base_class.py
- src/sas/sascalc/dataloader/readers/red2d_reader.py
This PR matches 5.x up to the 4.x branch by attaching a warning to any data set that is fully masked when it is loaded. The first of the two commits has already been merged into the ESS_GUI branch, but the 2nd commit (cherry-picked here) has not.
The PR for the 4.x branch: #1356 
The 1st PR for the 5.x branch: #1368
> ESS GUI: Warn user when data set fully masked

- src/sas/qtgui/Utilities/TabbedModelEditor.py
When loading plugin model with a spurious unicode character plugin editor crashes #1431
> Added utf-8 specs to open plugin file. Addressing #1431

- check_packages.py
As suggested yesterday, check_packages.py in master now compares the appropriate yaml file against what is currently installed on the users system. I've added two new dependencies that might need to be incorporated into the existing yaml files, but I only have a Windows system right now. The 5.x fix is a little more complex due to the number of yaml files in the branch so I haven't finished it yet.
Features:
- Checks the installed packages against the yaml file, including version numbers
- Flags packages that aren't installed as a major issue
- Flags packages with unexpected or unknown versions as a minor issue
Possible TODOs:
- Add PyYaml and colorama to the dependency files
> 4.x: Check packages comparison to YAML files

- docs/sphinx-docs/build_sphinx.py
Quick fix for docs being placed in a different directory than the main code during `setup build`
> Updated doc compilation location to match the main code

- src/sas/qtgui/MainWindow/DataExplorer.py
- src/sas/qtgui/MainWindow/UnitTesting/DataExplorerTest.py
Ready for review.
Fixed edge cases and added unit tests.
> Fixed the edge cases and added a beefy unit test. #1546

- src/sas/qtgui/Perspectives/Fitting/ComplexConstraint.py
- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
- src/sas/qtgui/Perspectives/Fitting/UnitTesting/FittingWidgetTest.py
fixes #1522 
Wrong behaviour was caused by a the PD value attributed to the checkbox state. Also added a test that will fail if the bug happens.
> Ess gui 1522 poly check

- src/sas/qtgui/MainWindow/MainWindow.py
Fixes #1560: SAS_DLL_PATH set on sasview startup if not already set in the environment
> Set SAS_DLL_PATH on sasview startup

- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
- src/sas/qtgui/Perspectives/Fitting/UnitTesting/FittingWidgetTest.py
Fixes #1538
Corrects some bugs on the polydispersity and adds some unit tests, updates `sasmodel` polydispersity with the GUI values, and also adds a mechanism that sets the `sasmodel` polydispersity to 0 whenever the polydispersity is unchecked in the GUI.
> Ess gui 1538 poly constraints

- src/sas/qtgui/Perspectives/Fitting/ComplexConstraint.py
- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
- src/sas/qtgui/Perspectives/Fitting/UnitTesting/ComplexConstraintTest.py
- src/sas/qtgui/Perspectives/Fitting/UnitTesting/FittingWidgetTest.py
Fixes #1545 
Removes tab names in the dict used for updating the fit page when pasting. Also adds unit tests for PR #1533
> Ess gui 1545 copy paste

- src/sas/sasgui/perspectives/calculator/gen_scatter_panel.py
* Fix infinite loop that appears in wxPhoenix.  Don't know why wx3 didn't complain.
* Make sure all widget handling is happening in the wx thread; the completion callback needs to trigger a call to the wx thread when it is convenient.
> fix wx4 problems with gen scattering panel

- src/sas/qtgui/MainWindow/DataExplorer.py
- src/sas/qtgui/MainWindow/GuiManager.py
- src/sas/qtgui/MainWindow/UnitTesting/MainWindowTest.py
- src/sas/qtgui/Perspectives/Fitting/FittingPerspective.py
- src/sas/qtgui/Perspectives/Fitting/UnitTesting/FittingPerspectiveTest.py
- src/sas/qtgui/Perspectives/Inversion/InversionPerspective.py
- src/sas/qtgui/Perspectives/Inversion/UnitTesting/InversionPerspectiveTest.py
The Inversion perspective can now be saved and loaded in project and analysis files. Also, all perspectives retain their information when changing between perspectives allowing project files to save state of all serializable perspectives at one time.
Closes #1578 
Works toward #1526 - Remaining: save/load Corfunc and Invariant perspectives
> Save inversion state in project and analysis files (ESS_GUI)

- src/sas/qtgui/MainWindow/DataExplorer.py
- src/sas/qtgui/MainWindow/UI/DataExplorerUI.ui
- src/sas/qtgui/MainWindow/UnitTesting/DataExplorerTest.py
- src/sas/qtgui/MainWindow/UnitTesting/GuiManagerTest.py
- src/sas/qtgui/Perspectives/Corfunc/CorfuncPerspective.py
- src/sas/qtgui/Perspectives/Fitting/ComplexConstraint.py
- src/sas/qtgui/Perspectives/Fitting/FittingPerspective.py
- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
- src/sas/qtgui/Perspectives/Fitting/SmearingWidget.py
- src/sas/qtgui/Perspectives/Fitting/UnitTesting/FittingPerspectiveTest.py
- src/sas/qtgui/Perspectives/Invariant/InvariantPerspective.py
- src/sas/qtgui/Perspectives/Inversion/InversionPerspective.py
Allows sending a data set to the active fit page via a checkbox in the `DataExplorer`, which will replace the current dataset. Performing the replacement will not delete any children of the replaced data set, as described in the linked issue.
Fixes #1537
> ESS_GUI: allow data replacement on a fit page

- test/sasdataloader/utest_red2d_reader.py
This fixes an issue with case-sensitive file systems that aren't able to find a test file introduced by PR #1619.
> Fix unit test with mixed case file name (wxPython)

- src/sas/qtgui/MainWindow/DataExplorer.py
- src/sas/qtgui/MainWindow/UnitTesting/DataExplorerTest.py
- src/sas/qtgui/Perspectives/Fitting/FittingPerspective.py
- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
- src/sas/qtgui/Perspectives/Fitting/UnitTesting/FittingPerspectiveTest.py
- src/sas/qtgui/Utilities/GuiUtils.py
- src/sas/qtgui/Utilities/UnitTesting/GuiUtilsTest.py
Fixes #1653 
This PR aims at having constraints applied when all fit pages are loaded when loading a project, instead of having them applied immediately after each fit page loading. This was causing problems as the GUI would complain that there where unknown symbols in the constraint if they were referring to parameters of a yet to be loaded fit page.
> Load constraints after fit pages when loading project

- src/sas/qtgui/MainWindow/DataExplorer.py
- src/sas/qtgui/MainWindow/DataManager.py
- src/sas/qtgui/MainWindow/GuiManager.py
- src/sas/qtgui/Perspectives/Corfunc/CorfuncPerspective.py
- src/sas/qtgui/Perspectives/Fitting/FitPage.py
- src/sas/qtgui/Perspectives/Fitting/FittingLogic.py
- src/sas/qtgui/Perspectives/Fitting/FittingUtilities.py
- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
- src/sas/qtgui/Perspectives/Fitting/ReportPageLogic.py
- src/sas/qtgui/Perspectives/Invariant/InvariantPerspective.py
- src/sas/qtgui/Perspectives/Invariant/InvariantUtils.py
- src/sas/qtgui/Perspectives/Invariant/UnitTesting/InvariantPerspectiveTest.py
- src/sas/qtgui/Perspectives/Inversion/InversionPerspective.py
- src/sas/qtgui/Utilities/GridPanel.py
- src/sas/qtgui/Utilities/GuiUtils.py
- src/sas/qtgui/Utilities/UnitTesting/GridPanelTest.py
The sample title is displayed in the data explorer instead of the file name. This is useful for distinguishing multiple data sets that are loaded from a single file.
This is the 5th PR separating #1559. I do not plan to create a parallel PR for v4.x/wxPython/master.
Closes #1243.
> Display sample title instead of filename in DataExplorer window (ESS_GUI)

- src/sas/qtgui/Perspectives/Fitting/ConstraintWidget.py
- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
- src/sas/qtgui/Perspectives/Fitting/UnitTesting/ConstraintWidgetTest.py
- src/sas/qtgui/Perspectives/Fitting/UnitTesting/FittingWidgetTest.py
Fixes #1654 : when fitting a single fit page with a constraint relying on another fit page, the constraint will just be disabled instead of being removed. The corresponding line in the constraint widget will be unchecked, so one can recheck if needed.
> Disable rather than remove constraint when fitting a single fit page

- .travis.yml
- build_tools/travis_build.sh
- docs/sphinx-docs/build_sphinx.py
- docs/sphinx-docs/source/conf.py
- docs/sphinx-docs/source/user/tools.rst
- setup.py
- src/sas/qtgui/GUITests.py
- src/sas/qtgui/Utilities/FileConverter.py
- src/sas/sascalc/dataloader/loader.py
- src/sas/sascalc/invariant/invariant.py
- src/sas/sascalc/pr/calc.py
Recent work updating the Debian packages for sasview indicated that the 5.0.0 release went out with tests that failed and documentation that couldn't be built. Some of these things were fixed immediately following the release while others have been in subsequent PRs.
Building the documentation and running `GUITests.py` on travis so that failures are visible earlier will make it easier to spot regressions and help improve the quality of the SasView releases.
This PR enables:
* building of the documentation on travis-ci; the documentation build throws a lot of warnings some of which are undoubtedly bugs to be fixed.
* running of `GUITests.py` (test runner for the Qt GUI); these tests currently fail on CI. Some of these will be easy to fix while some will not.
While this PR will cause the …
> Test more on travis-ci

- src/sas/qtgui/Perspectives/Fitting/ComplexConstraint.py
- src/sas/qtgui/Perspectives/Fitting/ConstraintWidget.py
- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
- src/sas/qtgui/Perspectives/Fitting/UnitTesting/ComplexConstraintTest.py
- src/sas/qtgui/Perspectives/Fitting/UnitTesting/ConstraintWidgetTest.py
This PR aims at improving the way constraints are handled:
* Enables constraint edition in the constraint tab. The edited constraint replaces the old one if the user does not make a mistake while entering it. If the constraint definition is faulty, changes are reverted and a dialog is shown giving information on the mistake.
* Forces a constraint parameter to be checked when the constraint is active. Fixes #1600 
* `Add all` button in the `ComplexConstraint` dialog constrains **all** parameters with the same name on both fit tabs. Fixes #1589 
* Adds an `All` option in the right combobox of the `ComplexConstraint` dialog as a quick way to set up constraints on the same parameter across all fit tabs e.g. `M1:radius = M4.radius`, `M2:radius = M4.radius`, `M3:radius = M4.radius` by selecting …
> Handling of constraints in v5.x

- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
- If the checkbox is clicked in a row which is NOT selected (dark background), only this row gets toggled
- If the checkbox is clicked in a row which is selected (one or many rows can be selected) all rows get toggled based on the content of the checkbox clicked.
This is hopefully less confusing for single row checks while maintaining extended selection applicability.
> A bit "smarter" extended selection checkbox toggle. #1676

- src/sas/sascalc/dataloader/readers/cansas_reader_HDF5.py
This fixes #1710. The h5py package v3.0 removed a previously deprecated method that was still present in the NXcanSAS reader. I tested this locally with h5py v2.8, v2.9, and v3.1. I did not update the version for h5py in the build and conda files but I'm not opposed to doing this.
> Ticket 1710: Remove deprecated method call from NXcanSAS reader

- .github/workflows/test.yml
- pytest.ini
As a starting point for #1644, here's a reimplementation of the existing .travis.yml as GitHub Actions. I started this as a proof of concept as part of the Hackathon... however, it is at feature parity with the travis testing at this point so it's probably ready for us to switch from Travis-CI to GitHub Actions right now. 
What it does:
- builds SasView, builds the documentation and runs tests on Ubuntu, Windows and macOS.
- install packages via pip (conda is not used); pip wheels are cached 
- runs GUI tests under Linux
What it does not yet do that travis does:
- report status to Slack - this looks easy enough to add but needs a slack workspace admin to do set up the web hook secrets
What it does not _yet_ do but travis doesn't either:
- build the Qt GUI under MacOS (wheels for pyuic5 …
> Run tests using GitHub Actions

- src/sas/qtgui/MainWindow/DataExplorer.py
- src/sas/qtgui/MainWindow/GuiManager.py
- src/sas/qtgui/Perspectives/Corfunc/CorfuncPerspective.py
- src/sas/qtgui/Perspectives/Invariant/InvariantPerspective.py
- src/sas/qtgui/Perspectives/Inversion/InversionLogic.py
- src/sas/qtgui/Perspectives/Inversion/InversionPerspective.py
This PR fixes a few issues related to plotting, most of which have to do with the Invariant Perspective.
- Fixes #1541: The invariant perspective now updates existing plots so a new window is not generated every time the calculator is run.
- Fixes #1542 and Fixes #1605: The invariant perspective no longer pulls the plot state from the DataExplorer so plots with similar names as Invariant plots are no longer plotted alongside the Invariant plots (same data name or same theory name like Corfunc).
> Various Invariant Plotting Fixes

- src/sas/qtgui/Perspectives/Invariant/InvariantPerspective.py
This forces the deletion of the high-q and/or low-q Invariant extrapolation plots when one has been previously calculated, but the user runs another calculation without that particular extrapolation selected.
This is the 4th PR in a chain of PRs for the invariant perspective: This -> #1716 -> #1715 -> #1709
fixes #1607
> Remove Invariant plots when extrapolations turned off

- .github/workflows/test.yml
A few minor tweaks to the new GitHub Actions 'test.yml' 
-  make it easier to spot problems in the documentation building (splitting the sasmodels and bumps doc builds from the sasview doc build); sphinx output is so long that being able to use the Actions bookmarks in it to view just the desired part is helpful
- make sure DISPLAY is set when building the SasView docs so that importing PyQt5 works
> Minor improvements to GitHub actions

- src/sas/qtgui/Plotting/SlicerParameters.py
- src/sas/qtgui/Utilities/GuiUtils.py
Any perspective creating child data and adding them to the datamanager now default to them being unselected. The user can unroll the tree and check whichever plots they would like to work with.
If a perspective needs to have the child plot it is creating and sending to the data manager selected instantly it will need to deliberately set the checkstate at Checked.  This should normally be avoided as it causes no end of confusion to the user.
This should resolve issue #1566.  I suspect this will reduce confusion on the Invariant as well and maybe other places.
Note to Reviewers. This also reverts the last commit in the slicer series PR #1721 that was merged a few days ago which did a manual force uncheck. That is no longer needed.  This was tested on win 10 only.
> Make new child plots unselected by default

- src/sas/qtgui/MainWindow/DataExplorer.py
- src/sas/qtgui/MainWindow/NameChanger.py
- src/sas/qtgui/MainWindow/UI/ChangeNameUI.ui
- src/sas/qtgui/MainWindow/UI/DataExplorerUI.ui
- src/sas/qtgui/MainWindow/UnitTesting/DataExplorerTest.py
A new option was added to the data explorer context menu allowing users to change the display name for a data set. The option opens a window offering 4 options: Keep the existing name, change to the data tile, change to the data file name, or change to any name the user would like. Unit tests were added to check base functionality and catch a few odd edge cases.
This fixes #1701 and closes #1702.
> Allow display name changes in data explorer (1702)

- src/sas/qtgui/MainWindow/NameChanger.py
UI initialization needed certain globals to be defined.
Moved those in front of the `setupUI` call.
> Move globals in front of the UI initialization to allow GUI to start #1760

- src/sas/qtgui/Plotting/Slicers/BoxSlicer.py
- src/sas/sascalc/dataloader/manipulations.py
This is a start at addressing #1344.  It only addresses the "folding" issue, and only for the boxslicer the code for which, as stated in the issue, was already present but was hard coded to `fold = True` in the GUI and `fold = False` in sascalc.
The GUI is particularly ugly at present in that the slicer parameter editor assumes all parameters are floats.  This works since any number other than 0 is true and 0 is false but ultimately allowing for a parameter by parameter editor would be the right answer making the fold boolean a checkbox.  This also is probably not possible for 5.0.4-rc1 in which case I would recommend that we merge this but keep the branch active. It still allows the functionality to be changed and should be a benign change?
> Slicer extension 1344

- src/sas/qtgui/Plotting/Plotter2D.py
- src/sas/qtgui/Plotting/Slicers/BoxSlicer.py
`box x` and `box y` interactors didn't have correct signatures for the `validate` method. Actual validation is not required at this stage, since values will be checked at apply time in the slicers and if incorrect, a meaningful message is displayed.
However, we need to at least define those methods properly...
> Define proper signatures for validate methods. Fixes #1766

- .github/workflows/test.yml
At the moment, pyopencl breakage on macos is preventing the tests being run on other platforms as the test matrix uses fast-fail by default.
> Try to run tests everywhere rather than fast-fail

- src/sas/qtgui/Perspectives/Fitting/FittingPerspective.py
This fixes a project load issue noted by @RichardHeenan in a [comment in 1689](https://github.com/SasView/sasview/issues/1689#issuecomment-768239201). This fixes the issue with loading projects with 3 (or more) fits. I am working on the errors thrown in another branch.
> 5.0.4 Project Load Fix

- src/sas/sascalc/dataloader/manipulations.py
The _Slab, Boxsum, Ring, and _Sector slicer calculators now exclude masked points from their calculations. The CircularAverage calculator already excluded such points.
NCNR VSANS data - annular average with masked data points included in the calculation (using release_5.0.4 branch):
NCNR VSANS data - annular average with masked data points excluded from the calculation (using this branch):
Note: No new unit tests were added. None of the current tests use masked data.
Fixes #1776.
> Exclude masked data points from slicer calculations

- src/sas/qtgui/Plotting/LinearFit.py
- src/sas/qtgui/Plotting/Plotter.py
- src/sas/qtgui/Plotting/SetGraphRange.py
This PR retains the graph range when data are replotted, e.g. after a second fit, and ensures the minimum value of a linear fit is always non-negative.
I built this off of `release_5.0.4` and am currently pointing this PR there, but this could also go into `main`.
Fixes #1750
> Retain graph range on redraws

- src/sas/qtgui/Plotting/LinearFit.py
- src/sas/qtgui/Plotting/UI/LinearFitUI.ui
The `Rg*Qmin` and `Rg*Qmax` are now displaying in the correct text boxes in the Linear Fit window. I also corrected the spelling of Guinier (from Guiner) in the window.
I built this branch off of release_5.0.4 instead of main. This PR should replace #1784 if we plan to add this to 5.0.4 RC3/final.
Fixes #1782
> Linear Fit Rg*Qmin & Rg*Qmax

- src/sas/qtgui/Plotting/SlicerParameters.py
The batch slicer was taking the first item in the `plot.data` list for 1D slicer plots when saving data. This would save data with the default slicer parameters.
This highlights a potential issue - the `plot.data` list for 1D plots is getting appended to every time slicers are redrawn without removing previous slices. I haven't had a chance to see if this extends to other 1D plots, but data is supposed to get purged from this list when data is updated.
This change should not affect functionality if the list is purged in the future. `list[-1] == list[0]` when `len(list) == 1`.
Fixes [point 14](https://github.com/SasView/sasview/issues/1772#issuecomment-776089648) in #1772
> Batch Slicer: Save Most Recent Slice

- installers/installer.iss
- installers/installer_generator64.py
This changes the INNO setup to always allow the user to select an installation path. This fixes [point 2](https://github.com/SasView/sasview/issues/1772#issue-795052995) of #1772.
Documentation on the flag I am adding: [DisableDirPage](https://jrsoftware.org/ishelp/index.php?topic=setup_disabledirpage)
The windows build server will need to be back online before this can be verified.
> Always show path selection on installation

- src/sas/qtgui/Perspectives/Corfunc/CorfuncPerspective.py
This fixes an issue noted in #1754 where the Corfunc perspective 'Real Space Correlation' plot is not reset on data deletion.
> Corfunc Perspective: Reset Plots on Data Deletion

- src/sas/qtgui/Plotting/QRangeSlider.py
Q-range sliders are redrawn when their linked inputs are changed. Previously, this only happened when the plot regained focus.
This fixes [point 9](https://github.com/SasView/sasview/issues/1772#issuecomment-776922573) of #1772.
> Force redraw of q-range sliders on input change

- src/sas/qtgui/MainWindow/DataExplorer.py
- src/sas/qtgui/MainWindow/UnitTesting/DataExplorerTest.py
Theory plots are now closed when theory data is deleted.
Fixes #1754 (last remaining issue related to the ticket)
> Close theory plots on theory deletion

- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
- src/sas/qtgui/Perspectives/Fitting/OrderWidget.py
- src/sas/qtgui/Utilities/GridPanel.py
This PR ensures the batch fit page logic element isn't orphaned when a batch fit page is created which rendered all Q range and dI options useless. This work also ensures the q-range isn't improperly reset after a batch fit. Plots can also now be found when clicking the Plot button from the batch fit window.
Fixes #1796
Fixes #1795
Fixes #1794
Fixes #1446
> Batch Fitting Fixes for Options and Plotting Issues

- build_tools/conda_qt5_win_commercial.yml
qtconsole=4.7.5
pyzmq=19.0.1
probably a bit too conservative, but this is what ran fine on 5.0.3
> Pin versions of qtconsole and PyZMQ to enable QtConsole.

- src/sas/qtgui/MainWindow/UnitTesting/DataExplorerTest.py
- src/sas/qtgui/MainWindow/media/data_formats_help.rst
- src/sas/qtgui/Utilities/GuiUtils.py
- src/sas/qtgui/Utilities/UnitTesting/GuiUtilsTest.py
- src/sas/sascalc/dataloader/readers/ascii_reader.py
- src/sas/sascalc/dataloader/readers/associations.py
- src/sas/sascalc/dataloader/readers/cansas_reader_HDF5.py
- src/sas/sascalc/dataloader/readers/csv_reader.py
- src/sas/sascalc/file_converter/nxcansas_writer.py
- test/sasdataloader/utest_ascii.py
Data1D can now be output in CSV format, and freeform file extensions can be provided by the user regardless of the file type selected in the save menu. Unit tests and documentation were modified and expanded to account for the changes I made.
Fixes #1780
> Add CSV Writer and Allow freeform file extensions

- src/sas/qtgui/Perspectives/Fitting/SmearingWidget.py
This changes how `SmearingWidget.py` determines which resolution should be used. The data checks that have been removed from the widget in this PR are already being performed in `src/sas/sascalc/fit/qsmearing.py`. On top of that, the checks were inconsistent in the two places.
fixes #1804
> 1804: Remove redundant checks so dx==0 is allowed

- docs/sphinx-docs/build_sphinx.py
- docs/sphinx-docs/source/conf.py
- src/sas/qtgui/Calculators/DataOperationUtilityPanel.py
- src/sas/qtgui/Perspectives/Fitting/FittingPerspective.py
- src/sas/sascalc/fit/Loader.py
The major reason for the current failure to build the sasview docs is sasmodels being monkeypatched into `sas.models`. Having loaded all the classes, sphinx knows that `sas.models` should exist but then can't actually load any source for them. That results in the rather odd errors that we have been seeing:
```
WARNING: autodoc: failed to import class 'sas.models.FlexCylEllipXModel' from module 'sas.sascalc.fit'; the following exception was raised:
…
AttributeError: module 'sas.sascalc.fit' has no attribute 'sas'                                                                                                                                                                         
```
Note that this PR is not enough to actually make the documentation build cleanly, with the following 19 …
> Doc building fixes

- src/sas/qtgui/MainWindow/DataManager.py
- src/sas/qtgui/MainWindow/NameChanger.py
- src/sas/qtgui/MainWindow/UnitTesting/DataExplorerTest.py
The display name dictionary `DataManager.data_name_dict` was changed from `{str: int}` to `{str: [int]}` to better track display names. The dictionary is now purged whenever data is deleted or a display name is changed. Unit tests were updated to account for this change.
Fixes #1757 and [point 5](https://github.com/SasView/sasview/issues/1772#issuecomment-768257509) of #1772.
This could wait until post 5.0.4 final, but this branch is based of `release_5.0.4`.
> Limit adding [n] to name on data load and name change

- build_tools/conda_qt5_min_osx.yml
- build_tools/conda_qt5_min_ubuntu.yml
- build_tools/conda_qt5_win_commercial.yml
When trying to create env from yml file with recent versions of conda it throws thousands of warnings:
`Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.`
I observed it on OSX and added pip to developers build (min file). It needs to be explored for other platforms.
> Adding pip dependency to yml file so that conda doesn't complain

- .github/workflows/docs.yml
- .github/workflows/installers.yml
- .github/workflows/test.yml
First step towards #1855 is to see what we can already do in the GitHub Actions CI for tests, docs and installer, which this PR does.
* the pytest tests pass (with the usual failures not actually causing the tests to fail!)
* the GUI tests still fail in the normal ways and that failure is suppressed
* building the docs succeeds
* building the installer succeeds (but that is not the same as saying that the installer works)
The installer is at https://github.com/llimeht/sasview/actions/runs/852749020 if windows and mac users would like to test it out.
> Add py3.9 remove py3.6 from github actions

- build_tools/conda_qt5_min_ubuntu.yml
- build_tools/conda_qt5_win_commercial.yml
Since conda package is conflicting and cannot be resolved I am trying with pip installable package
> Adding h5py=3.1 as a pip package

- src/sas/qtgui/Perspectives/Inversion/InversionPerspective.py
- src/sas/qtgui/Perspectives/Inversion/UnitTesting/InversionPerspectiveTest.py
This PR fixes a handful of bugs associated with the P(r) Inversion perspective.
- The logic for activating the parameter buttons (No. of Terms and Reg. Constant) has been simplified. They are active whenever data is loaded and no calculation is occurring. Fixes #1742 
- The manual background input is now accepted and the toggle is not switched to manual input after every fit. Fixes #1765
- A few unticketed save/load issues, namely values not being updated properly, were also fixed.
- A few of the unit tests were fixed or updated but a couple of tests in the `inversionPerspectiveSuite` are throwing errors that I was unable to fix here. Refs #1732
This branch was built off of `release_5.0.4`, but this PR could wait until after 5.0.4 final.
> Various P(r) GUI Fixes

- src/sas/qtgui/Utilities/CodeEditor.py
- src/sas/qtgui/Utilities/TabbedModelEditor.py
- src/sas/qtgui/Utilities/UI/ModelEditor.ui
- src/sas/sasview/__init__.py
Also, replaced QTextEdit with a nicer editor, with line number printout and current row highlight
Addresses issue #1800
> Syntax checker in the model editor.

- src/sas/qtgui/MainWindow/DataExplorer.py
a simple extra option passed to the file open widget apparently fixes it for some.
https://bugreports.qt.io/browse/QTBUG-13182?focusedCommentId=201836&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-201836
> Attempt to address file load widget sluggishness issue. #1866

- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
- src/sas/qtgui/Perspectives/Fitting/UI/FittingWidgetUI.ui
- src/sas/qtgui/Perspectives/Fitting/UnitTesting/FittingWidgetTest.py
This PR adds a 'Compute' button to fit pages and limits recalculation to when the user presses this button, or hits the Enter or Return keys. This matches the behavior in 4.2.2.
Refs #1767
> Add Compute Button and Limit Fitting Computations

- .gitignore
- src/sas/sascalc/calculator/sas_gen.py
- test/sascalculator/utest_sas_gen.py
Use np.column_stack() to correctly arrange the outputted data for the sld file, so that it is in the correct order.
> minor change to sas_gen.py which should fix #1886

- src/sas/sascalc/dataloader/readers/cansas_reader.py
- test/sasdataloader/data/cansas_xml_multisasentry_multisasdata.xml
- test/sasdataloader/utest_cansas.py
The CanSAS XML reader now properly loads in multiple SASdata elements held within a single SASentry element. Unit tests were added to ensure this remains true.
fixes #1889
> canSAS XML Reader: Load multiple SASdata in a single SASentry

- src/sas/qtgui/Calculators/GenericScatteringCalculator.py
This PR adds a cancel button to the generic scattering calculator to cancel computations between each chunk of Q values. If the computation is cancelled the remainder of the Iq values are filled in with `NaN`. The ticket for this request suggests using `calcthread.isquit()`, however the current code uses twisted.internet threads as opposed to the calcthread class in sasview. As far as I can tell there is no inbuilt way to detect an interruption in these threads, so a boolean flag is used. Upon cancelling the calculation the compute/cancel button becomes disabled until the current chunk of Q values have been computed.
Currently the areas of the graph with `NaN` values are simply not updated, which can cause odd effects on the graph when cancelling a calculation. This is because the …
> Ticket 1406 cancel calculation

- src/sas/qtgui/Calculators/GenericScatteringCalculator.py
- src/sas/qtgui/Calculators/UI/GenericScatteringCalculator.ui
- src/sas/qtgui/Utilities/GuiUtils.py
- src/sas/sascalc/calculator/geni.py
- src/sas/sascalc/calculator/sas_gen.py
This branch contains commits to resolve #1825 . The primary changes are to allow the user to select nuclear and magnetic data from two separate files, and carry out a full calculation of the expected scattering pattern given this. As part of this the following key functionality was added:
- The ability to load in two separate files for nuclear and magnetic SLD data, along with verification that the two files contain data about the same points in 3D space.
- The ability to select a constant value for an sld which is not loaded as a file. For example a magnetic sld datafile can be loaded and a constant nuclear scattering value given to each point.
- Small tweaks to the gui to make it more responsive to the user - e.g. empty textboxes now reset to their last valid value if they lose focus, …
> Ticket 1825 scattering calc

- src/sas/sascalc/fit/BumpsFitting.py
As discussed in issue #1914, the pull request from #1682 lead to fitting error in SasView. This pull request attempts to accomplish the same goal of propagating errors on constrained parameters by using code inspired by #1682, while avoiding the fitting issues that lead to #1914.
> Using the uncertainties module to propagate errors

- src/sas/qtgui/Plotting/ColorMap.py
- src/sas/qtgui/Plotting/UnitTesting/ColorMapTest.py
- src/sas/qtgui/Plotting/rangeSlider.py
This pull request fixes ticket 1928. The right slider to change the maximum value of the colour range in 2D plots was linked to the minimum values. Effectively both sliders did the same. The behaviour is now also checked correctly in the ColorMapTest.
> Fix Color Map Slider in 2D plots

- src/sas/qtgui/Perspectives/Fitting/media/fitting.rst
This PR pushes a fix for failing doc builds because of : sasview/docs/sphinx-docs/source-temp/user/qtgui/Perspectives/Fitting/sesans/sesans_fitting.rst: WARNING: document isn't included in any toctree
> Re-create toc entry for sesans_fitting in sasview

- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
- src/sas/qtgui/Perspectives/Fitting/UnitTesting/FittingWidgetTest.py
- src/sas/qtgui/Perspectives/Fitting/plugin_models/__init__.py
- src/sas/qtgui/Perspectives/Fitting/plugin_models/plugin_structure_template.py
- src/sas/qtgui/Perspectives/Fitting/plugin_models/plugin_template.py
Fixes the bug in SasView v5 that resulted in the structure factor combo box of the gui not listing plugin models also labeled as a structure factor. This was described in issue [#1852](https://github.com/SasView/sasview/issues/1852).
> Fixes missing plugin models from structure factor combo box

- src/sas/qtgui/Plotting/Plotter.py
- src/sas/qtgui/Plotting/PlotterBase.py
This uses a version parsing package bundled with setuptools (no extra dependencies) to help fix the 'nonposy' issue in MPL version > 3.3 that is used for the Github actions build.
> Use version parsing package for MPL version check

- src/sas/qtgui/Plotting/QRangeSlider.py
This fixes the issue noted in slack regarding an error when running a linear fit. This same error was also thrown when closing any plot with q-range sliders.
The signal used to link the GUI input to the sliders was changed from `textChanged` to `editingFinished`, but the disconnection was not changed to match.
> Q-Range slider fix for linear fits

- src/sas/qtgui/Utilities/PlotView.py
handle newer versions (>3.3.1) of matplotlib, where _activeQue is not defined
> Fix for removed _activeQue in newer Matplotlib

- src/sas/sascalc/dataloader/readers/associations.py
Noted in [PR #1933](https://github.com/SasView/sasview/pull/1933#discussion_r739280429), the .sesans file extension is not associated with the sesans reader. This fixes the issue.
I would be willing to add a unit test if desired.
> Add .sesans extension to associations.py

- .github/workflows/installers.yml
Addition to gh actions installer to store artifacts on https://github.com/SasView/sasview/releases
Drafts are avaialable only for logged in users (and I believe bellonging to SasView organization). Regular users will see releases and pre-releases as before. Artifacts will be stored for each branch and will be updated once new change is pushed to the code, which could keep the list of managable size. As discussed with @butlerpd after merging branch entry on the list should be removed (currently plan to do it manualy but can probably be also done through gh actions).
> Gh actions artifacts

- src/sas/qtgui/MainWindow/GuiManager.py
- src/sas/qtgui/Plotting/QRangeSlider.py
- src/sas/qtgui/Plotting/UnitTesting/QRangeSliderTests.py
This PR removes the global variable LOADED_PERSPECTIVES introduced since the release of 5.0.4. The perspective is found from the parental hierarchy of the Plotter class, instead. Unit tests were updated to account for the change.
fixes #1972
> Remove global variable LOADED_PERSPECTIVES

- src/sas/sascalc/calculator/geni.py
The calculation of the magnetic scattering length density does not conserve handedness. The magnetic scattering length assumes always a positive magnetisation in the magnetic scattering component for the SF channel. This is fine for collinear structures, but might run into issue for some non-symmetric cases, when M(-x)=-M(x).
> fix handedness of magnetic structures in mag SLD

- src/sas/qtgui/Utilities/GuiUtils.py
When saving projects, some scalar quantities (e.g. `numpy.float32` and `numpy.float64`) were unable to set a default when saving the value, so a message was pasted into the console log saying `data cannot be serialized to json`. This fixes that issue.
No associated ticket. Originally noted in an email by @smk78 during testing of 5.0.5rc1.
> Save project: Properly handle scalars

- src/sas/qtgui/Calculators/GenericScatteringCalculator.py
Same solution as elsewhere in code - don't interpret/display directory icons in the file load widget.
Apparently this leads to serious performance issues for very large directories.
> Change default options on file load widget to not display dir icons.

- .github/workflows/installers.yml
- .github/workflows/release.yml
The latest version of PyQt (5.15) is not statble on Mac OSX. Version 5.13 seems to be stable (tested by few users). 
As discussed at the call this PR also fixes scipy to 1.7.3 (for all platforms).
> Switching to PyQT 5.13 

- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
- src/sas/qtgui/Perspectives/Fitting/ModelThread.py
Bring intermediate results back when smearing is on and display radius_effective. #2009
After all this was a SasView issue, although it did look like it originated in SasModels...
This assumes SasModels returns properly smeared P(Q) and S(Q) so we don't have to do it in `ModelThread` as it is currently done. Quick test shows this is the case but more careful check should be done before merge.
`100nmPinholeSphere` file, sphere/sphere/hardsphere, fitted `radius` only.
left: existing 5.0.5rc2, right: from this PR
> radius_effective update for smeared data

- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
Added a simple conditional in the list comprehension for filling the model combobox with model names.
This can be easily removed once rpa works again.
Note: this only removes RPA from the model list on the fitting widget. It is still present in the Category Manager.
> Don't show RPA in the list of models #2022

- src/sas/qtgui/Perspectives/Fitting/UnitTesting/FittingWidgetTest.py
- src/sas/sascalc/calculator/geni.py
- src/sas/sascalc/calculator/sas_gen.py
Orientation angles are θ, φ, ψ  but magnetic orientation uses up_angle and up_phi. Rename up_angle to up_theta for consistency
Verify that θ, φ use the same orientation system as the particle axis, both for applied field and for orientation of the magnetism within the particle.
> Call magnetic angles up_theta 

- src/sas/qtgui/Perspectives/Fitting/FittingPerspective.py
- src/sas/sascalc/fit/BumpsFitting.py
This uses the id for the MPFit engine as the default name when generating the fitting window since this optimizer is now the default. If we want to remove the old `scipy.leastsq` option from the Fit Options combobox we could add something like the following to src/sas/sascalc/fit/BumpsFitting.py at line 17 (credit @pkienzle).
>`try:`
>`FIT_ACTIVE_IDS.remove(fitters.LevenbergMarquardtFit.id)`
>`except ValueError:`
>`pass`
refs #2036
> Use MPFit fitter as the default fit engine

- src/sas/qtgui/Calculators/DataOperationUtilityPanel.py
Plots generated by the Data Operation tool did not have the `id` attribute set. This attribute is used as a dict key when saving plots to the project json file.
Added the id attribute.
A more correct way would be to have this (and other, required) attributes defaulted in the Plotter initializer, so they are always present. This should be a part of the plot rewrite story, mentioned elsewhere
> Add id to the generated plot. #2098

- src/sas/qtgui/convertUI.py
This change is for a small improvement to the resource and UI building step in `run.py`.
Instead of requiring `pyrcc` and `pyuic` scripts be present in the PATH, the main run script is now importing necessary modules.
This also avoids using os.system() calls which are potential security issue.
Patch supplied by @pkienzle 
This fixes #1060
> Resource and UI compilation is now path-independent.

- build_tools/requirements.txt
- src/sas/qtgui/Utilities/Reports/reports.py
> Added missing dependencies to requirements.txt

- src/sas/qtgui/MainWindow/DataExplorer.py
- src/sas/qtgui/Perspectives/Corfunc/CorfuncCanvas.py
A few imports were missed in #2141. The `DataExplorer` imports are only used in rare cases and the `CorfuncCanvas` was merged into main while the PR was open.
Refs #2172
> Missed sas.sascalc.dataloader imports

- .github/workflows/installers.yml
As described in #2213, we are in the very strange situation of making a new release out of every single git push, and they are all published on the releases page. That is polluting the [releases page](https://github.com/SasView/sasview/releases) with lots of weird stuff ~~to which users should never be subjected~~ (Edit: not visible to not logged in users, fortunately; but still not pleasant!).
Building an installer to test can (and does!) work via the actions. They are published as artifacts of the particular action run and are visible under the "Summary" of the action once it has run. Making a release isn't needed to make those installers available For example: [https://github.com/SasView/sasview/actions/runs/3113602635](https://github.com/SasView/sasview/actions/runs/3113602635)
I …
> Stop making a new release on every push

- src/sas/qtgui/Utilities/GuiUtils.py
Embedded latex ends up with lots of backslashes that need to be protected as raw strings rather than (mis)interpreted as standard C-style escape sequences.
> Fix incorrect escape sequences

- docs/sphinx-docs/source/user/RELEASE.rst
- docs/sphinx-docs/source/user/marketplace.rst
This PR updates the URLs in the SasView documentation pointing to the Model Marketplace from http to https now that the Marketplace has been updated.
> Update marketplace urls to https

- .github/workflows/installers.yml
- .github/workflows/release.yml
- build_tools/requirements.txt
- installers/sasview.spec
debugpy isn't used anywhere in the sasview code or in the documentation/examples; bundling it into the installer requires additional fragile workarounds, so if it's not needed, can we drop it?
> Drop debugpy from installer

- src/sas/qtgui/MainWindow/GuiManager.py
- src/sas/qtgui/Perspectives/Fitting/ViewDelegate.py
- src/sas/qtgui/Perspectives/Invariant/InvariantDetails.py
This PR attempts to improve compatibility with newer Qt/PyQt releases. Several functions regarding progress bar values and pixel positioning that used to accept `float` now only accept `int`. The C++ Qt documentation for these functions uniformly says that the arguments should be `int`; I'm not sure whether the failures observed are due to changes in Qt or PyQt, and they may even be architecture-specific. 
I expect that there are more changes like these needed, as I found these spots just by wandering through the interface loading dialogues and hitting "fit" or "compute" buttons.
Platform: Linux (Debian)
Python: 3.10
Qt: 5.15.7
PyQt: 5.15.4
> Qt 5.15.4 compatibility

- build_tools/requirements.txt
Fixing typo in the pytest-mock. The bigger question is we can put this file under CI i.e. replace pip lines in ymls with `pip install -r build_tools/requirements.txt`?
> Fixing typo in build_tools/requirements.txt

- installers/sasview.spec
The pyinstaller spec file sometimes needs to contain workarounds for packages to help pyinstaller find all the relevant imports or data files. If such introspection is still needed, we should avoid baking in platform-dependent and python-version-dependent paths. 
This PR makes use of the `sysconfig` module from the [Python stdlib](https://docs.python.org/3/library/sysconfig.html) that has information about where packages are located, so the details of `lib` vs `Lib`, `site-packages` vs `dist-packages`, `python3.8` vs `python3.10`,… all go away. This last one is very important as it means we can create installer artifacts with multiple different Python versions for testing purposes, without needing to change the spec file.
I tested an earlier version of this patch with Windows and Linux …
> Generalise pyinstaller spec paths 

- docs/sphinx-docs/source/user/working.rst
- src/sas/qtgui/MainWindow/DataManager.py
- src/sas/qtgui/Perspectives/Fitting/media/fitting.rst
- src/sas/qtgui/Perspectives/Fitting/media/fitting_help.rst
- src/sas/qtgui/Plotting/Arrow3D.py
This PR fixes some more Sphinx warnings generated during the full doc build.
> Update rst strings to fix doc build warnings

- src/sas/qtgui/Plotting/Plotter.py
Fixes #2253 by switching Plotter to use data.name as the default `label` for a plot item rather than `data._title`.  `data.name` changes with the "Change Name" option in the Data Explorer.
> Support custom data names in plot legends

- installers/sasview.spec
- src/sas/system/log.py
Using `__file__` to find resources is hopelessly complicated across the different frozen modules, debug modules, unpacked source etc that are used to run sasview. `importlib.resource` provides a uniform interface to finding resources that are shipped alongside modules.
There are plenty of other places where this transformation needs to be made; this is the first one that annoyed enough as it was causing issues with the installer.
Since the `config_file` member is not used anywhere outside this class, let's also make it 'private' since it's a file-like object that should be private to the module.
> Stop using __file__ to find logging config

- src/sas/qtgui/Plotting/Plotter.py
Fixes #2267 by commenting out calls to `matplotlib.pyplot.cla()` which were already paired with the more specific alternative calls to `self.ax.cla()` (at best a duplicate, at worst it causes arbitrary plots to blank themselves as seen here.
It would be worth eyes from @rozyczko and @krzywon who wrote this originally to see if there's some reason I'm missing for the `plt.cla()` call.  It seems to now work fine on my machine.  The tell, even without a way to reproduce, is that when data is "Compute/Plot"'d on Main the plot briefly will flash to a white background with default axes from 0 to 1, linear, on both axes.  That no longer happens on this branch, at least for me.  Or see reproduction instructions in #2267.
> Fit intermittent plot blanking (#2267)

- src/sas/qtgui/Calculators/UI/SldPanel.ui
Set min width on squishable elements
> SLD calculator tool buttons

- src/sas/qtgui/Utilities/Preferences/PreferencesPanel.py
showHelp is defined on the gui manager not on the main window.
> Fixed showHelp reference

- src/sas/qtgui/MainWindow/DataExplorer.py
Append additional runtime extensions to a copy of config.PLUGIN_STATE_EXTENSIONS value, not config value itself.
Fixes growing config file issue noticed in @wpotrzebowski's config.json
> Modify copy of config.PLUGIN_STATE_EXTENSIONS value, not config value

- src/sas/qtgui/MainWindow/AboutBox.py
- src/sas/qtgui/MainWindow/UI/AboutUI.ui
- src/sas/qtgui/MainWindow/UnitTesting/AboutBoxTest.py
In order to facilitate finding path for running sasview from script: #2280 it has been added to about box. 
Some minor fixes (like correcting link to contributors list) has also been introduced.
> Adding installation path to about box

- installers/installer.iss
A tiny bit of code within the installer configuration allows the installer to be run as a completely non-interactive installer allowing for later automation:
```
./setupSasView.exe /SP- /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /ALLUSERS /SKIPLICENSE=true /LANG=english /NOICONS /TASKS='' /LOG=install.log /DIR=C:/somewhere/
```
Automated testing of the Windows installer needs this to land first.
> Add cli option to installer to skip licence dialogue

- src/sas/sascalc/fit/BumpsFitting.py
Simple fix of a typo: 1800 (seconds) should be 18000 in the if block deciding which is the best format to print out the remaining calculation time
> Improve output format for the fitting log (#2276)

- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
Use the new perspective class methods that replaced the old copy/paste methods.
Fixes #2319
> 2319: Fix copy/paste when selecting a structure factor

- src/sas/qtgui/MainWindow/UnitTesting/GuiManagerTest.py
- src/sas/qtgui/MainWindow/UnitTesting/MainWindowTest.py
- src/sas/qtgui/Utilities/Preferences/UnitTesting/PreferencesPanelTest.py
Some tests were broken during recent merges. This does some cleanup.
> Fix up some tests that were broken during codecamp

- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
- src/sas/qtgui/Perspectives/Fitting/ModelThread.py
Fixes #2327 by adding an optional flag to Data1D objects `isExpData` marking actual, experimental data and differentiating it from models/residuals.  The plotting routines inside `Fitting` then use this flag to differentiate these two datatypes.
Edit: just uses plot role instead of new flag.
> Add flag for experimental data and gate plotting on it

- src/sas/qtgui/Perspectives/Fitting/ModelThread.py
This fixes a binning bug for sesans data.
Sesans is in real space and the Hankel transform from q space to real space (spin echo length) was implemented as a resolution function. For other resolution functions, the qmin and qmax range is compared to data.x which are all in q space. This is then passed to the calculator to return the unsmeared Iq. However, for sesans data, qmin, qmax, and data.x are all in real space while the calculator is expecting q space data to return the unsmeared Iq (which will then get passed to the sesans "smearer" which uses the hankel transform to convert Iq to real space).
Due to the number of points in q_calc (in q space) being much greater than the number of points in q (spin echo length in real space) in the sesans transform (resolution function), this …
> Fixes binning bug in implementation of sesans data

- src/sas/qtgui/Perspectives/Fitting/FittingUtilities.py
Fixed the SESANS residuals plot so they show in real space rather than q space.
Fixes #2337 
Plotting residuals for SESANS and regular SAS data.
> fixed sesans residuals plots to show in real space rather than q space

- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
This fixes a bug in the SasView gui that was switching the slit length and slit width values when using a structure factor for a slit smeared dataset after switching the resolution to "Custom Slit Smear" and then back to "Use dQ Data". 
This closes #2333. Recent changes were made to the slit smearing functions and nomenclature, and so @pbeaucage and @butlerpd should take a look.
Load a slit smeared dataset that includes the slit length, select a form factor and structure factor, go to the resolution tab, switch from "Use dQ Data" back to "Custom Slit Smear" and then back again. I've also tested for other datasets with different dQ data and also using different combinations of all resolution options and form factor models with and without structure factor.
> Fix "Use dQ Data" bug that swtiched slit length and slit width in the gui

- src/sas/system/log.ini
The disable-by-default strategy of dealing with console messages turned out to be unpopular. Going with the original strategy of just dumping h5py messages into the ether.
Fixes: Paul Butler
Closes #2323
> Back to explict blacklisting of h5py messages

- src/sas/qtgui/MainWindow/MainWindow.py
Re-add the resources (rc) for the MainWindow which was incorrectly removed in 11a1ef2fb231d6b1c0b456bb998b63616f806dff. Without it, there are no icons in the main toolbar, the main window icon or the sub-window icons. 
Closes: #2363
> Re-add rc file to MainWindow.py

- src/sas/qtgui/MainWindow/DataExplorer.py
- src/sas/qtgui/Utilities/ResultPanel.py
The Bumps convergence window now closes when the data it shows is deleted. This also updates the results panel title to show the same name as the data explorer and fit panel.
Fixes #2350
Steps I followed:
- Loaded a data set
- Sent to fit and ran fit using LM
- Verified convergence window is displayed
- Deleted data set and verified convergence window no longer shown
- Loaded three data sets (data1, data2, and data3)
- Sent data1 and data2 to fitting
- Fit data1 using LM and verified convergence window is displayed for data1
- Fit data2 using LM and verified convergence window is displayed for data2
- Delete data1 and verified the convergence window still displays data2
- Delete data3 and verified the convergence window still displays data2
- Delete data2 and verified convergence window …
> 2350: Close the BUMPS/DREAM results panel when data is deleted

- src/sas/qtgui/Perspectives/Invariant/UI/TabbedInvariantUI.ui
- src/sas/qtgui/Perspectives/Invariant/UnitTesting/InvariantPerspectiveTest.py
- src/sas/sascalc/invariant/invariant.py
As described in #2334 two issues related to invariant perspective were identified. The firts issue with read only fields for Qmin and Qmax should be fixed now. However the other problem is more deconvoluted as it is related to the fact that we calculate invariant based on `(scale * data) - background`, which requires correct setting for scale and background. As it turned out for apoferitin example the values coming from fitting may be over/underestimated and therefore Q* may become negative. Warning has been added to the code suggesting checking backround and scale value. In the future we may consider more inteligent guidance.
I've checked documentation. It seems to be consitent but maybe we should add note about scale/background issue? 
Fixes #2334 
1) Load data set 
2) Send to Invariant …
> Fixes in invariant prespective

- src/sas/qtgui/MainWindow/media/preferences_help.rst
- src/sas/qtgui/Utilities/Preferences/DisplayPreferencesWidget.py
- src/sas/qtgui/Utilities/Preferences/PlottingPreferencesWidget.py
- src/sas/qtgui/Utilities/Preferences/PreferencesPanel.py
- src/sas/qtgui/Utilities/Preferences/PreferencesWidget.py
- src/sas/qtgui/Utilities/Preferences/UI/PreferencesUI.ui
- src/sas/qtgui/Utilities/Preferences/UnitTesting/PreferencesPanelTest.py
- src/sas/system/config/config_meta.py
- src/sas/system/config/schema_elements.py
This hopes to combine parts of what was done in #2306 and #2321, specifically related to formalizing the preferences panel and widget class structures.
As asked for in #2316, the following has been added to this PR:
- Settings are staged in the preferences panel until they are accepted and only then is the config updated (using the OK or Apply buttons)
- All staged changes are discarded if they are rejected (using the Close button or X)
- Restore defaults resets the active widget to the default values as read in from the configuration
- Added 'Cancel' and 'Apply' buttons
- Updated the help documentation to include expected behaviors and information on specific
Fixes #2312
Fixes #2313
- Unit tests that are in this PR
- From `run.py`:
- Open preferences, modify settings, click Cancel, open …
> 2316: Refactoring preferences

- src/sas/sascalc/pr/p_invertor.py
This is the first of what is to be many PRs for the release of 5.0.6. This is a cherry-pick of the single commit in #2178 to fix broken P(r) inversion functionality and unit tests.
> [Release 5.0.6] Cherry-picked 2178 - Breaking bug in P(r)

- .github/workflows/installers.yml
- .github/workflows/release.yml
Updated GH actions for release. It is set so it only triggers build when PR is created and updated. It should be sufficient with Installer workflow doing essentially the same job. 
This PR uses old approach to GH actions, which we decided to run for 5.0.6. Main branch has different mechanism (merged at the last code camp).
It can only be tested from installers and logs.
> Updated release gh actions

- .github/workflows/installers.yml
Fixing typo in installer yml. The branch name starts with "installer" not "release" to trigger installer.yml workflow.
> Installer 5.0.6 GitHub actions

- src/sas/qtgui/Calculators/KiessigPanel.py
- src/sas/qtgui/Calculators/UI/DataOperationUtilityUI.ui
- src/sas/qtgui/Calculators/UI/DensityPanel.ui
- src/sas/qtgui/Calculators/UI/GenericScatteringCalculator.ui
- src/sas/qtgui/Calculators/UI/KiessigPanel.ui
- src/sas/qtgui/Calculators/UI/ResolutionCalculatorPanelUI.ui
- src/sas/qtgui/Calculators/UI/SldPanel.ui
- src/sas/qtgui/Calculators/UI/SlitSizeCalculator.ui
- src/sas/qtgui/MainWindow/UI/AboutUI.ui
- src/sas/qtgui/MainWindow/UI/CategoryManagerUI.ui
- src/sas/qtgui/MainWindow/UI/ChangeCategoryUI.ui
- src/sas/qtgui/MainWindow/UI/ChangeNameUI.ui
- src/sas/qtgui/Perspectives/Corfunc/UI/CorfuncPanel.ui
- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
- src/sas/qtgui/Perspectives/Fitting/UI/ConstraintWidgetUI.ui
- src/sas/qtgui/Perspectives/Fitting/UI/FittingWidgetUI.ui
- src/sas/qtgui/Perspectives/Fitting/UI/OptionsWidgetUI.ui
- src/sas/qtgui/Perspectives/Invariant/UI/TabbedInvariantUI.ui
- src/sas/qtgui/Perspectives/Inversion/UI/TabbedInversionUI.ui
- src/sas/qtgui/Plotting/UI/ColorMapUI.ui
- src/sas/qtgui/Plotting/UI/MaskEditorUI.ui
- src/sas/qtgui/Plotting/UI/PlotLabelPropertiesUI.ui
- src/sas/qtgui/Plotting/UI/SlicerParametersUI.ui
- src/sas/qtgui/Utilities/UI/AddMultEditorUI.ui
- src/sas/qtgui/Utilities/UI/PluginDefinitionUI.ui
This PR addresses one of the issues brought up in https://github.com/orgs/SasView/discussions/2342 and spun off into https://github.com/SasView/sasview/issues/2385.
Now, tab order for all widgets in SasView is consistent and goes in standard direction (left->right, up->down)
Fixes #2385
> 2385 incosistent tabbing order across the widgets

- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
- src/sas/sascalc/fit/BumpsFitting.py
As described in [bumps/bumps#58](https://github.com/bumps/bumps/issues/58) and #1999, when the initial fit values are set outside the fitting bounds, the MPFit (L-M) and Quasi-Newton fitters fail to converge and may throw errors. This utilizes the bumps `FitDriver.clip()` feature to coerce the initial values within the bounds prior to fitting. A warning is logged when any values are coerced.
Fixes #1999
This fix should also be added to v5.0.6 once it's reviewed.
Run SasView, select the L-M (MPFit) optimizer, load a data set, send it to fitting, and select a model. From there, I tried 2 different things
1. Set the fit range of one of the parameters to not include the initial value. This was done by changing both the upper a lower limits.
2. Set the initial value of one of the parameters so …
> 1999: Clip fitting values set outside the fit range

- src/sas/qtgui/MainWindow/UI/MainWindowUI.ui
1) Renamed "Tool" menu to "Tools"
2) Some re-ordering of menu contents
Fixes #2412 
I ran it and the menu looked like I specified in QtDesigner
> Tool[s] menu reorganised and renamed

- .github/workflows/ci.yml
- .github/workflows/matrix.py
Ubuntu v18.04 was removed from the CI.
Fixes #2398 
CI ran successfully
> Remove ubuntu 18.04 from CI

- src/sas/qtgui/Plotting/Plotter.py
Residual plots should now have 2 red lines at +/- 3 sigma and 2 dashed gray lines at +/-1 sigma.  There does not seem to be any documentation that needs updating.
The only change necessary for this was to use the `data1D_plot_role` already established. This allows the fix to require only a small 5 line block of code in the `PlotterWidget` in `plotter.py`.  Basically if `data.plot_role==data1D.ROLE_RESIDUAL` then add 4 horizontal lines (`ax.axhline()`). 
Fixes #1329
by running in developer environment
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
Load a data set (AOT microemulsion for example), send to fitting, choose a model (e.g. sphere/core_shell_sphere), hit compute/plot and/or fit (after choosing some parameters to fit).  The …
> Add +/- 1 and 3 sigma lines on residual plots

- src/sas/qtgui/Perspectives/Corfunc/CorfuncPerspective.py
- src/sas/qtgui/Perspectives/Corfunc/ExtractionCanvas.py
- src/sas/qtgui/Perspectives/Corfunc/RealSpaceCanvas.py
- src/sas/qtgui/Perspectives/Corfunc/UI/CorfuncPanel.ui
- src/sas/qtgui/Perspectives/Corfunc/util.py
- src/sas/sascalc/corfunc/calculation_data.py
- src/sas/sascalc/corfunc/corfunc_calculator.py
- src/sas/sascalc/corfunc/extrapolation_data.py
- src/sas/sascalc/corfunc/transform_thread.py
- test/corfunc/utest_corfunc.py
Various improvements to corfunc:
1) More robust calculation of inflection point, existing method was numerically unstable
2) Added different ways of extracting parameters
3) Added a diagram showing how the parameters are calculated (like in Fibre_Diffraction_Review_1994_3_25-29)
4) Bug fix: extrapolation range was incorrect
Fixes #2444 
Fixes #2445
Tested on a couple of example data files.
> Improvements to Corfunc

- .github/workflows/installers.yml
- .github/workflows/release.yml
- src/sas/qtgui/MainWindow/GuiManager.py
Pinning ipykernel and qtconsole version
Fixes #2452
Locally, with the installer from https://github.com/SasView/sasview/actions/runs/4426851089
> Console fix 5.0.6

- .github/workflows/release.yml
- src/sas/sascalc/dataloader/manipulations.py
`data.err` can be None for certain plots, like residuals.
This should be checked when data.err is being subscripted.
Note - correct handlers for `None` are present in subsequent code.
Fixes #2436
Tested locally
> Fix for 1D operations on 2D residual plots

- run.py
- setup.py
- src/sas/qtgui/convertUI.py
This adds new arguments to convertUI.py and setup.py to force all UI elements to be rebuilt, regardless if they exist or not. This is partly in response to the cleanup needed to test #2478 but could also have utility for future dependency changes.
Ran `python convertUI.py -f`, `python setup.py rebuild_ui`, and `python setup.py clean`, and all 3 rebuilt the UI elements regardless if they existed or not.
> Add argument to convertUI that forces full UI rebuild

- run.py
This removes the UI generation step to ensure all environments are able to start the SasView application using `run.py`.
Fixes #2510
Ran `python run.py` from the base sasview directory and the application launched.
> Remove UI conversion from run.py

- src/sas/qtgui/Plotting/Plotter.py
The math import was reinstated to Plotter.py.
Fixes #2516
Run SasView and plot data -> no more errors in the console!
> Reinstate math import to Plotter.py

- src/sas/qtgui/Calculators/UnitTesting/DensityCalculatorTest.py
Recently, while attempting to run the GUI tests locally, `pytest` fails with an `no module 'pytest' on line 36 of DensityCalculatorTest.py` error. This fixes the error.
There is no associated issue.
Run `python -m pytest -v -s src/sas/qtgui` from the base sasview directory and the tests run again.
> Import pytest in density calculator GUI tests

- src/sas/qtgui/Perspectives/Fitting/ConstraintWidget.py
- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
Addresses #2525. This PR contains fixes to slot checking and checkbox setting.
Locally, Win10
> C&S fitting widget fixes for PySide6

- src/sas/qtgui/Perspectives/Fitting/ConstraintWidget.py
- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
- src/sas/qtgui/Utilities/GridPanel.py
Simple change to point to the proper location of QAction
Fixes #2530
Locally Win10
> Reparent QAction from QtWidget to QtGui (PySide6)

- src/sas/qtgui/Utilities/GuiUtils.py
a `getSaveFileName` call managed to squeak by unchanged from the Qt5 version.
In Qt6, there is one more positional argument needed.
Additionally, checked all the other occurrences of this call to make sure we're done here.
Fixes #2533 
Local tests on Win10
> Fix for save dataset error #2533

- src/sas/qtgui/convertUI.py
This RP makes the PySide6 script names in converUI.py all lowercase, as their respective script names on Linux systems are all lowercase. Without this change, 'command not found' errors are produced when SasView is installed or run by following the dev environment setup instructions given in the wiki.
Fixes #2542 
The changes were made and found to get rid of the errors, allowing SasView to install and run correctly on both Arch Linux and Ubuntu. I have not personally tested the effect of these changes on Windows or MacOS, but wpotrzebowski and piotr have informed me via Slack that both upper and lower case work for both of these operating systems, so this change should not cause any problems.
> Lowercase PySide6 executables for Linux compatability #2542

- .github/workflows/ci.yml
- .github/workflows/matrix.py
- build_tools/requirements.txt
- pytest.ini
Fixing OSX build from the main branch. It is pyside2 that is problematic and therefore it was removed from requirements (keeping only PySide6). 
It also updates the version of Python and the installer. These were probably not required, but it will be a useful update if it works on all platforms.
#2541 
Installer downloaded and tested.
> 2541 nightly build artifact doesnt start on mac

- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
This adds a simple check for polydisperse parameters for the chosen model.
If there are such parameters, the polydisp checkbox and the polydisp tab are enabled.
Fixes #2551 
Local tests on windows
> Polydisperse parameter check on model load

- src/sas/qtgui/MainWindow/GuiManager.py
- src/sas/qtgui/Utilities/SasviewLogger.py
Fix found by @pkienzle. Fixes issue stemming from move to Pyside6 from pyqt5, where the Log Explorer stopped working after the switch. Previously, there were two instances of the function `emit()` that were inherited into the handler- one from logging.handler, and one from QObject.
Fixes #2538 
Run Sasview. Log messages should now show up in the Log Explorer.
> Log explorer fix

- src/sas/qtgui/MainWindow/DataExplorer.py
When counting instances of plots, one needs to be careful with QtWidget parentage being updated.
The existing Manager->Plotter->PlotterWidget chain was working with Qt5 (and from what I remember was necessary to achieve correct MDI space location) but started failing with Qt6.
Getting rid of `Plotter` and instantiating `PlotterWidget` directly seems to be safer.
Fixes #2527
local testing on win10
> Avoid parenting mess by calling the widget directly

- src/sas/qtgui/Utilities/GuiUtils.py
- src/sas/qtgui/Utilities/Reports/ReportDialog.py
- src/sas/qtgui/Utilities/UnitTesting/GuiUtilsTest.py
Unit coversion for GUI widgets is now based on sasmodels RST_PROLOG struct.
This struct is read in and parsed in GuiUtils to create a dictionary which is then used to convert ASCII units into HTML for display in the parameters table, report document and its serialized versions.
Several units, missing from rst_prolog were explicitly added and can/will be removed when sasmodels is updated.
Fixes #2561 
Local tests on win10.
> unit conversion for gui is missing

- src/sas/qtgui/Plotting/Slicers/WedgeSlicer.py
The 1D plots created by the new `WedgeSlicer` now returns:
* Properly converted radians to degrees for the x scale
* The default scale for both x (phi) and y (intensity) are linear.
* The Angular range is pi to pi (with 0 pointing along the positive x axis) as per the normal python and sasview convention
NOTE: this was tested and works well with uncommitted changes to manipulation.py in sasdata needed to fix the actual averaging. This can still be tested with sasdata/master I think as long as one does not allow the wedge to straddle the negative x axis. This should not affect merging since that problem exists in the current main of sasview.
NOTE2:  The caveat to the angular range is that when the wedge straddles the negative x axis the phi max will be greater than 2pi but the data will be …
> Adjusts scale and angular range in 1D plots from WedgeSlicer

- src/sas/qtgui/MainWindow/DataExplorer.py
When fixing #2527, I failed to spot a conditional checking the 2D plotter class. This is now fixed. I found no other direct comparison of Plotter[1,2]D in the relevant code.
Fixes #2586
Locally, dev version on Win10
> Plot2D instances are now of `Plotter2DWidget` type. Fixes #2586

- src/sas/qtgui/Calculators/DensityPanel.py
- src/sas/qtgui/Calculators/GenericScatteringCalculator.py
- src/sas/qtgui/Calculators/ResolutionCalculatorPanel.py
- src/sas/qtgui/Calculators/SldPanel.py
Several calculators didn't limit the max size of the dialog, making it possible to resize them silly.
This fixes it.
Fixes #2437
Local win10 build
> fix dialog sizes for some calculators. #2437

- build_tools/requirements.txt
- setup.py
- src/sas/system/log.py
This pull request removes the unused dependency `h5py` from the `requirements.txt` and  `setup.py` configuration files. Moreover, the`log.py` is updated to ensure there are no references to `h5py`. The removal of this dependency is a finding from ongoing research aimed at identifying and eliminating code bloat within software projects.
Initially, the project incorporated the `h5py` library. However, over time, the codebase evolved, and currently the library is unused. Still, the package continues to be listed in the project's dependency files. Removing this unused dependency reduces the overall footprint of the application, mitigating potential security risks, and simplifying the dependency management process.
> Remove Unused Dependency: h5py

- src/sas/qtgui/Plotting/Slicers/BoxSlicer.py
- src/sas/qtgui/Plotting/Slicers/WedgeSlicer.py
This commit fixes the mismatch between the `_post_data` method signatures in BoxInteractor and WedgeInteractor and their child classes. It also removes an unnecessary argument from one `_post_data` call, as it only sets a parameter to its default value. This fixes an error that occurs when the 'fold' setting is changed in Box Interactor X and Box Interactor Y's Slicer Parameters menu.
Fixes #2588
The check-box can now be checked and un-checked without causing the error, and the plot updates accordingly.
> Fixed unmatched method signatures in Box&Wedge Interactor child classes

- src/sas/qtgui/Calculators/DataOperationUtilityPanel.py
This fixes a (post-5.0.6) bug in the Data Operation Panel, where datasets would not load properly. 
Fixes #2591 
Local dev version on Win10
> Pass the Data1D/2D object, not its `data` attribute

- .github/workflows/ci.yml
- .github/workflows/nightly-build.yml
Moving OSX signing to nightly builds, so that builds work from forks
Install builds from PR and nightly
> Moving OSX signing to nightly

- src/sas/qtgui/MainWindow/CategoryManager.py
- src/sas/qtgui/MainWindow/DataExplorer.py
- src/sas/qtgui/MainWindow/UnitTesting/DataExplorerTest.py
Qt6-ize the setFilterRegularExpression syntax, such that the empty row in DataExplorer display of datasets is not shown.
Fixes #2642
> Empty lines in data explorer

- .github/workflows/ci.yml
CI started to pull pyinstaller 6, which is messing up the Windows install generating a single file exe.
This started right when we finished the code camp...
The proper solution is to find out what changed in the default parameters and modify the SPEC file to not generate a single executable but the "normal" file tree.
GH windows build
> PyInstaller pinned

- .github/workflows/ci.yml
When multiple instances of the same CI are queued, the existing one should be stopped in favor of the newer CI.
> Stop existing concurrent CI

- src/sas/qtgui/Calculators/SlitSizeCalculator.py
- src/sas/qtgui/Perspectives/Fitting/FittingUtilities.py
- src/sas/sascalc/fit/AbstractFitEngine.py
New behaviour in numpy>=1.25 deprecated `== []` comparisons. Those were present in several places in the code, causing havoc in fitting, among others.
https://numpy.org/doc/stable/release/1.25.0-notes.html
**THIS WILL HAVE TO BE CHERRY PICKED TO THE RELEASE BRANCH**
Fixes #2650
Locally and with GH installer (Windows)
> Fixes for the new numpy syntax

- src/sas/qtgui/Calculators/SlitSizeCalculator.py
- src/sas/qtgui/Perspectives/Fitting/FittingUtilities.py
- src/sas/sascalc/fit/AbstractFitEngine.py
Fixes for the new numpy syntax (cherry picked from main)
> Cherry-picked new_numpy_behaviour

- build_tools/requirements.txt
'html5lib' was listed twice in `requirements.txt`. This removes one of those instances.
**Question** Do we still need the `html5lib`? Grep shows the only other place it is listed in the entirety of SasView is in setup.py.
> Remove duplicate `html5lib` from requirements file

- .github/workflows/ci.yml
- build_tools/release_notes/6.0.0_notes.txt
This PR addresses two issues related to continuous integration for release_6.0: 1) It uses GH action that allows notarization with notarytool (compare to atool that won't be supported fron Nov 1st). 2) It automatically uploads release notes (so they don't disappear when upload action is pushed). We will need to make a decision whether this right approach for keeping GH release notes in the future. (One can still edit release page on GH and this file won't be aware of it). 
Installed sasview from installer file and checked if it runs (and if it is signed)
> Release 6.0.0 notes

- installers/sasview.spec
- src/sas/qtgui/Utilities/Reports/ReportDialog.py
- src/sas/qtgui/Utilities/UnitTesting/ReportDialogTest.py
Pyside6 uses print_() for QTextDocuments, rather than print().
Fixes #2675 
Locally and installer on Win10
> Fit report save fix

- src/sas/qtgui/Utilities/GridPanel.py
This fixes and old bug where some extra semicolons added an empty line to the available save formats for grid files in batch fitting
Fixes #2676
Locally on win10
> Fix for empty save format for grid files

- src/sas/qtgui/MainWindow/media/preferences_help.rst
This PR updates the preferences documentation to include information on the residual and polydispersity plotting preferences added in #2558.
Fixes #2679
> 2679: Update preferences documentation

- .github/workflows/ci.yml
By reducing which pushes fire CI to only the default branch and version tags, PR builds will not get two versions of each build.
The documentation for being more specific on branches/tags for a push is [here](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-branches-and-tags).
Refs #2378
Look at builds on #2647 for comparison (36 builds). This does not have builds for `push`, only `pull_request` is present (18 builds).
> Change build rules to not double fire on PRs

- .github/workflows/ci.yml
This points the CI to use the sasdata release branch [release_0.9.0](https://github.com/SasView/sasdata/tree/release_0.9.0) instead of the master branch.
CI
> Point to sasdata release branch

- src/sas/qtgui/Calculators/DataOperationUtilityPanel.py
- src/sas/qtgui/Calculators/DensityPanel.py
- src/sas/qtgui/Calculators/GenericScatteringCalculator.py
- src/sas/qtgui/Calculators/KiessigPanel.py
- src/sas/qtgui/Calculators/ResolutionCalculatorPanel.py
- src/sas/qtgui/Calculators/SldPanel.py
- src/sas/qtgui/Calculators/SlitSizeCalculator.py
- src/sas/qtgui/MainWindow/AboutBox.py
- src/sas/qtgui/MainWindow/Acknowledgements.py
- src/sas/qtgui/MainWindow/CategoryManager.py
- src/sas/qtgui/MainWindow/NameChanger.py
- src/sas/qtgui/Perspectives/Fitting/ComplexConstraint.py
- src/sas/qtgui/Perspectives/Fitting/GPUOptions.py
- src/sas/qtgui/Perspectives/Fitting/MultiConstraint.py
- src/sas/qtgui/Plotting/AddText.py
- src/sas/qtgui/Plotting/ColorMap.py
- src/sas/qtgui/Plotting/LinearFit.py
- src/sas/qtgui/Plotting/MaskEditor.py
- src/sas/qtgui/Plotting/PlotLabelProperties.py
- src/sas/qtgui/Plotting/PlotProperties.py
- src/sas/qtgui/Plotting/ScaleProperties.py
- src/sas/qtgui/Plotting/SetGraphRange.py
- src/sas/qtgui/Plotting/WindowTitle.py
- src/sas/qtgui/Utilities/AddMultEditor.py
- src/sas/qtgui/Utilities/FileConverter.py
- src/sas/qtgui/Utilities/ModelEditor.py
- src/sas/qtgui/Utilities/PluginManager.py
- src/sas/qtgui/Utilities/Reports/ReportDialog.py
- src/sas/qtgui/Utilities/TabbedModelEditor.py
Option `WindowContextHelpButtonHint` seems to have disabled the "close window" cross icon in PySide6.
The original reason for it was, as the name suggests, the removal of the question mark icon, which by default was set.
Fixes #2688 
GH Windows installer on Win10 and Win11.
> Re-enabled "close window" option on modal dialogs

- .github/workflows/ci.yml
- .github/workflows/nightly-build.yml
- build_tools/code_sign_osx.py
- installers/sasview.spec
Fixing nightly build but not fully resolving an issue related to running workflows by developers from outside sasview organization. Trying to move signing to nightly_build.yml didn't work and therefore there is only notarization step done there. It seems that we may enable runs from outside developers by changing run trigger from pull_reguest to pull_reaquest_target. However, as far as I understand there is a security risk associated with it. I am not comfortable with making such a decision. 
This PR also changes names of linux and OSX packages to SasView6 (tar.gz, app and dmg). The question is whether we shouldn't drop this numbering for easier maintenance in the future. It may be however confusing for users that have multiple versions installed (at least on MAC).
> Nightly builds fix

- src/sas/qtgui/Utilities/TabbedModelEditor.py
This PR fixes the date format appearing in the "Authorship and Verification" section of the generated user model. Before the fix, the dates were displayed as `2024YYY-01m-16d`. After the fix, they look like: `2024-01-16`.
It's part of the https://github.com/SasView/sasview/wiki/ContributorCampXII camp.
The fix was tested by comparing the output of the generated models before (with v6.0.0-alpha1) and after the fix.
> FIX: fix model date format in the user model docstring

- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
Some of the logic was incorrect, when setting the single-parameter constraint and when querying the underlying model information.
Now, item query returns proper parameter names, and the context menu is properly constructed (i.e. no "Edit constraint" on simple value constraint added)
Fixes #2695 
Local dev build on Win10
> Constraint on parameter raises error

- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
reinitialize self.kernel_module on category change.
Fixes #2692
Local win10 build
> Fixed context menu in the fitting widget

- test/utest_sasview.py
Previously the `logging` library was looking for a config at `test/system/log.ini` when the file was actually located in `src/sas/system/log.ini`, which made it crash upon startup. Note that this was already fixed when running single tests, so it is likely an oversight. Usually tests are run using pytest which isn't affected by this, and thus it has flown under the radar for quite a while. 
https://github.com/SasView/sasview/issues/2746
This only affects running all tests locally with the command `python test/utest_sasview.py`. Without this commit, it doesn't work.
> 2746 fixed running tests locally

- INSTALL.txt
After adding #2576 the requirements for Python version changed. We now need >=3.11.
This spells it out explicitly in the INSTALL.txt instructions.
> Explicit requirements for Python 3.11

- src/sas/qtgui/Plotting/Plotter2D.py
- src/sas/qtgui/Plotting/Slicers/AnnulusSlicer.py
- src/sas/qtgui/Plotting/Slicers/BoxSlicer.py
- src/sas/qtgui/Plotting/Slicers/SectorSlicer.py
- src/sas/qtgui/Plotting/Slicers/WedgeSlicer.py
Fixes slicer related bugs previously reported
For #2100:
- Adds the updateSlicer function in Plotter2D.py (primarily affects theoretical 2D data)
For #2726:
- Changes alpha (which was likely an angle) to theta in SectorSlicer.py
For #2752:
- Removes the group_id property from the plots as it functionally a duplicate of id. This change also eliminated the incorrect group_id in SectorSlicer.py that caused it to identify as the circular average
- Adds type_id which for all slicers is set to "Slicer" + name of the 2D data. This is used with an addition to setSlicer in Plotter2D.py to identify old slicer plots and remove them from the list. This will not remove the plot window, but will prevent it from reappearing if closed and the 2D data is replotted (primarily affects theoretical 2D data) …
> 2100 2726 2752 slicer bugfixes

- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
- src/sas/qtgui/Perspectives/Fitting/UI/FittingWidgetUI.ui
This PR addresses a criticism aired in #2390 that Users seem confused by what type of average our polydispersity distributions represent, even though this is clearly stated in the docs and on our FAQ webpage. The specific request was that something be added to the UI.
The solution provided is shown here:
Tested as a developer build on W10/x64.
> Define distributions on the UI

- src/sas/qtgui/Utilities/TabbedModelEditor.py
This fixes the issue related to loading c fils into the tabbed model editor introduced by the merge of #2576.
Fixes #2715
> 2715: C files not loaded in tabbed model editor (6.0.0a)

- src/sas/qtgui/MainWindow/GuiManager.py
Closes the actual subwindow object, not the active window, when switching perspectives, to ensure the window is closed.
Fixes #2789
> 2789: phantom perspective windows

- run.py
This PR prioritizes sibling packages over installed packages when launching run.py. This should better enable developers to modify sibling packages without the need for pip installation. This fix only applies to sasmodels, sasdata, bumps, and periodictable, but could be generalized to any package held in requirements.txt.
> Run.py: Prioritize sibling modules over installed modules

- .github/pull_request_template.md
Tried to make the PR checklist more usable... now like this
**Installers**
> Edited PR template

- src/sas/qtgui/Utilities/AddMultEditor.py
- src/sas/qtgui/Utilities/DocRegenInProgess.py
- src/sas/qtgui/Utilities/DocViewWidget.py
- src/sas/qtgui/Utilities/UI/DocRegenInProgress.ui
- src/sas/sascalc/doc_regen/makedocumentation.py
- src/sas/sascalc/doc_regen/regenmodel.py
- src/sas/sascalc/doc_regen/regentoc.py
Several issues related to the documentation editor are fixed with this pull request.
Fixes #2719 - Plugin model documentation is now built and displayed as expected.
Fixes #2727 - SasView now starts if the documentation has not been built, which was the underlying cause of the error.
Fixes #2733 - No longer seeing the index error.
Tested locally and tested the installer from the latest push.
> 2719, 2727, 2733: Documentation Editor Fixes

- docs/sphinx-docs/build_sphinx.py
- src/sas/qtgui/MainWindow/PackageGatherer.py
- src/sas/qtgui/Utilities/GuiUtils.py
- test/run_one.py
This is a `cherry-pick` of the commits from #2807 in a branch built off `release_6.0.0`. A quick functionality review should be done.
> 2806 [6.0.0]: Remove imp module

- src/sas/qtgui/convertUI.py
Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.
Fixed issue: convertUI does not create a outfiles when a space is present in a folder of the path. The issue was fixed properly quoting the files name in the convert UI.
Fixes #2791 
After this change,  run.py can start the application
> Quote file names in ConvertUI

- .github/workflows/ci.yml
- .github/workflows/matrix.py
As mentioned in #2812, the CI system was previously failing for ubuntu (latest). Though the problem seems to have solved itself, this PR ensures it will not happen again.
> Fix Ubuntu (latest) tests

- src/sas/qtgui/convertUI.py
Fixed forgotten comma and missing import statement from previous merge
The installer CI build output was checked for errors. Note that last time the build failed with a traceback but created an artifact (that could not open) anyway and gave a green "passed" checkmark.  This time no errors were visible.
Next, the windows installer was downloaded and the program started. opened some docs and then tested the new doc viewer by opening he doc for a plugin model. Since this change only affects the path (to avoid issues with a space in the path etc) in the UI builder, the fact that the UI.py files built properly suggests that it all works.
- [X ] There is **nothing** …
> fix problem with starting due to UI issue

- src/sas/qtgui/Calculators/GenericScatteringCalculator.py
Base QWidget class was being initialized twice leading to the Generic Scattering Calculator throwing on `Draw`.
Fixes #2818
Local win10 tests
**Installers**
> Don't initialize the base class twice

- src/sas/qtgui/Utilities/DocViewWidget.py
- src/sas/sascalc/doc_regen/makedocumentation.py
This takes `os.path` out of typing and replaces it with `os.Pathlike`
- [ x ] There is **nothing** that needs documenting
**Installers**
> Fix issue related to path typing

- docs/sphinx-docs/source/user/RELEASE.rst
- src/sas/qtgui/Perspectives/Fitting/media/fitting_help.rst
Same pull request as in pr #2844 , but this time against release_6.0.0
Examples of load_model_info usage in fitting_help.rst and release.rst needed to be fixed. Blank spaces in method call causes an error.
Searched in files for other appearences of load_model_info besides fitting_help.rst itself and fixed all blank spaces in the occurring strings. Fixes issue #2805 
Local build test on win10, tried old version with blank spaces and new version without blank spaces while the old version throws the mentioned error and the new version executes without errors.
**Installers**
> Corrected appearences of load_model_info example string in fitting_help.rst and release.rst

- src/sas/qtgui/MainWindow/DataExplorer.py
- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
Added logic to DataExplorer.py, in which the current tab is changed upon calling loadFromURL() in DataExplorer.py 
Fixes issue #1524
local win10 build, loaded data and tab changed
**Installers**
> 1524 when loading data the data explorer should revert to the data tab

- src/sas/qtgui/MainWindow/media/preferences_help.rst
- src/sas/qtgui/Plotting/PlotterBase.py
- src/sas/qtgui/Utilities/Preferences/PlottingPreferencesWidget.py
- src/sas/system/config/config.py
Same changes as mentioned in pull request #2845 
Added documentation changes in preferences_help.rst as suggested in #2845 
Added a checkbox in Preferences/Plotting Settings for using the matplotlib toolbar. Therefore edited the config and added USE_MATPLOTLIB_TOOLBAR.
Fixes issue [https://github.com/SasView/sasview/issues/1726](https://github.com/SasView/sasview/pull/url) , where access to the standard matplotlib toolbar is requested.
Local win10 build, tried plotting with and without the checked checkbox in the preferences. Both worked. Not sure, why the toolbar was disabled by default. Maybe that has to be checked.
**Installers**
**Licencing** (untick if …
> 1726 allow user to choose default for plot navigation tools - merge into release_6.0.0

- src/sas/qtgui/Perspectives/Fitting/GPUOptions.py
Cherry picked commit from https://github.com/SasView/sasview/pull/2842 rebased against `release_6.0.0`
> Add a button group to allow for proper logic of radio buttons

- src/sas/qtgui/Calculators/SldPanel.py
- src/sas/qtgui/Calculators/UI/SldPanel.ui
- src/sas/qtgui/Utilities/GuiUtils.py
Issue #2800 contains discussion about the best realization of the checking mechanism behind the chemical formula in the sld calculator. Before, the formula was checked with every key input, which resulted in a lot of errors in the logs.
Now the recalculate button is reintroduced and other signals for recalculating have been disabled. Neither hitting enter in the text box nor key inputs in a text box will trigger the formula checking anymore.
Fixes #2800 (issue/issues)
Trying the recalculation button functionality has been tested on local branch checkout build with win10. Test with installer will follow.
Edit: i wanted to test, but the _cdflib error has not been resolved on main yet, so the program wont execute …
> 2800 sld calculator allow user to finish typing

- .github/workflows/ci.yml
- installers/installer.iss
This uses the latest version of `pyinstaller` for all OSes, allowing the latest version of `scipy` on MacOS.
Fixes #2546
Fixes #2846 (once the release branch is merged back into main).
I downloaded the installer for both MacOS and Windows and they both launched. More testing is likely required.
**Installers**
> Pyinstaller 6

- .github/workflows/ci.yml
- .github/workflows/nightly-build.yml
Our builds are throwing a number of warnings every time a CI runs due to the deprecated version of the `node.js` module being used by the older versions of `actions/setup-python` and `actions/checkout`. The latest version are using the upgraded node.js
Note: that line 38 of `nightly-build.yml` was using `actions/setup-python@v1` instead of v4. It was also incremented to v5 but we should pay attention here - though it will likely have no affect until merged to main?
Fixes #2810 
TBA (needs to build) 
**Installers**
> Fixes problem with using deprecated node.js

- .github/workflows/ci.yml
- .github/workflows/matrix.py
It is now down to one warning, which cannot easily be fixed due to dependent action. 
Removing warnings created by GH actions and dropping support for python 3.9 in tests (as it seems to be not available on `latest-macos` runners https://github.com/actions/setup-python/issues/850)
> Warnings removals and python 3.9 drop in tests

- src/sas/qtgui/Utilities/TabbedModelEditor.py
A flag was added to the TabbedModelEditor to differentiate documentation edits from model edits. This stops the editor attempting to generate the documentation when saving a model.
In the future, the two editor types should be different classes (#2863).
Fixes #2855
Tested 
**Installers**
> 2855: Fix model save error

- src/sas/qtgui/MainWindow/GuiManager.py
Log view shows on level 30 now instead of 40.
Removed unnecessary passes
> 2875 drop logger level required to force log explorer to pop up from error to warning

- .github/workflows/ci.yml
Automated binary signing of the installer with ESS Digicert credentials
Local checks
**Installers**
> Added automated signing of the Windows installer

- src/sas/qtgui/MainWindow/GuiManager.py
The links to tutorials from the document editor don't work because they're PDF files, and it can't open them
I've changed the tutorial opening behaviour to back to just opening a web link as it did before.
I've opened an issue for updating the editor to handle PDFs - #2926 
fixes #2908
> Tutorials open in browser to avoid PDF failure

- src/sas/qtgui/Perspectives/Fitting/GPUOptions.py
Updated the path to GPU help to reflect recent changes made to documentation
Fixes #2909 
Checked on windows
**Installers**
> 2909 gpu options help button throws error

- test/sascalculator/utest_sas_gen.py
AUXSAS has tests that rely on random numbers without setting a seed, this will (and has) cause random test failures.
Set seed
Fixes #2976
Tests passing will test it
> 2976 auxsas has nondeterminstic tests

- src/sas/qtgui/Calculators/DensityPanel.py
This removes an unneeded signal that was throwing an error when the DensityPanel was running a calculation.
Fixes #2981
Tested locally
**Installers**
> 2981: Eliminate Errors on Density Panel Calculation

- src/sas/qtgui/Calculators/GenericScatteringCalculator.py
- src/sas/qtgui/MainWindow/GuiManager.py
GenericScatteringCalculator instantiation in GuiManager includes importing `sas.sascalc.calculator.geni`.
This module has been extensively "numbaised" and its import is very slow due to numerous JIT decorators.
The simplest/safest solution seems to be postponing the import until the GSC is actually needed.
Price paid: starting the GS calculator takes now a long time.
Fixes #2999 
Local testing on win10
- [ X] There is **nothing** that needs documenting
**Installers**
> 2999 Fix slow startup time

- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
This adds a check to see if the fit tab is able to be fit when a data set is sent to the tab.
Fixes #2988
**Installers**
> 2988: Check if Fit button should be enabled when data is sent to a fit tab

- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
A change to the PD params resulted in `width`, `npts`, and `nsigmas` to all change `width` of the underlying model. This corrects that behavior.
Fixes #2741
**Installers**
> 2741: Fix PD parameter issue

- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
The multiplicity row is set to 0 by default, which is the `scale` parameter. When loading a project, this row is ignored because it is handled elsewhere. This sets the row to -1 if there is no multiplicity parameter.
Fixes #2979
**Installers**
> 2979: Ensure multiplicity row is set when loading projects

- .github/workflows/ci.yml
Rework code that starts the linux installer bundle so that it correctly tests if the installer is functional. (Duplicating this PR since PRs from external forks now fail CI due to installer signing)
1. Fix the test harness to correctly detect sasview failing to start
2. Add additional packages to installation so that sasview can start
Fixes #2816
CI
1. fails to start: https://github.com/SasView/sasview/actions/runs/10470305752
2. now starts: https://github.com/SasView/sasview/actions/runs/10470744795
**Installers**
> Check successful launch of sasview on CI (linux)

- src/sas/system/config/config.py
This changes the default settings to show the mpl toolbar, and to not show polydispersity plots.
Fixes #3057
**Installers**
> 3057: Change default settings

- src/sas/qtgui/MainWindow/DataExplorer.py
This resets the data transforms held by the Data objects on the creation of new plots.
Fixes #1783
Refs #3021
Running from source, I tested plotting, changing scale, zoom, etc. I then replotted the same data in multiple ways (fit, new plot) and the new plots display in their default state.
**Installers**
> 1783: Reset transforms for new plots

- src/sas/qtgui/MainWindow/GuiManager.py
- src/sas/qtgui/Perspectives/Fitting/ConstraintWidget.py
- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
For some fitting failures, the result object is either None or an empty list. This causes unhandled behaviour and cryptic messages to the user.
Fixes #2994 (well, not actually fixes it but helps with diagnosis)
Local Win10 build
**Installers**
> Better checks on result object so failed fitting is shown as such.

- src/sas/qtgui/MainWindow/DataExplorer.py
This displays a message while a project file is loading. I'm not convinced this should be for 6.0.0, but it is a small change.
Fixes #2914
Tested locally and from the push installer (Windows)
**Installers**
> 2914: Display messages to show project file is loading

- src/sas/qtgui/Plotting/Plotter.py
Sometimes when the x array for plotting is empty (empty dataset?), an exception is thrown. This fix should address the immediate problem. There still may be the issue of why the empty arrays are passed to plotting in the first place, though.
Fixes #3085 
Local win10 build
**Installers**
> check for empty arrays #3085

- src/sas/qtgui/Utilities/DocViewWidget.py
Documentation window now displays the path of the file currently loaded in its title bar, which changes when the user navigates to a different file.
**NOTE:** If it is decided to display only the title of the documentation as opposed to the filepath, I have already implemented this in branch [2832-documentation-viewer-identify-file](https://github.com/SasView/sasview/tree/2832-documentation-viewer-identify-file). 
Fixes #2832 
Tested on Mac but not on Windows--I may have overlooked something to do with windows pathing.
**Installers**
> Documentation Window Identify Loaded File

- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
This takes the fix applied in #2991 a step further. The original fix did not account for the error column, and continued to modified the `.width` param regardless of the value changed.
Fixes #3016
Tested locally - different function produce different shape distributions.
**Installers**
> 3016: Fix to PD changes

- installers/installer.iss
This shows a custom message to the user whenever they choose an existing directory. If the user continues the installation, all files and folders are deleted from the directory.
Fixes #3030
Downloaded the windows installer and tested it works.
**Installers**
> 3030: Delete all files in installation directory

- src/sas/qtgui/MainWindow/DataExplorer.py
Fixed the issue of data manager keeping references to old, deleted datasets and unified the warning messages for various data deletion paths.
Fixes #3015
Local Win10 build.
**Installers**
> Fixed querying of the data dict at the removal step. Fixes #3015

- src/sas/qtgui/MainWindow/DataExplorer.py
Use the standard Yes/No buttons for the QMessageBox instead of homebuilt ones. This fixes an issue where the user could click 'No' in a pop-up message and not cancel future actions.
Fixes #3091
Triggered the message box to load by loading a data set and then selecting 'File' -> 'Load Project'. I then clicked the 'No' button and the prompt returned me to SasView and no data was removed.
**Installers**
> 3091: Use standard buttons in QMessageBox

- src/sas/qtgui/MainWindow/GuiManager.py
- src/sas/qtgui/Utilities/WhatsNew/WhatsNew.py
Previously, on my Ubuntu machine, the what's new page would appear behind the main window. This is problematic because the user will not immediately see the what's new page, and also the main window will not be responsive until the what's new window has been closed. This caused me a lot of confusion initially.
The reason for this is because the what's new parent is being set to the GuiManager not the MainWindow, and also this parent does not get passed to the QDialog instance thus QT doesn't internally know about its parent.
One thing that perhaps should be discussed is whether this fix should be implemented for any other windows/widgets in the application. I noticed other widgets are using GuiManager as their parent but wasn't sure if this was intentional, and I only wanted to apply the …
> Make the what's new page appear in front of the main window on Linux

- src/sas/qtgui/Plotting/Plotter.py
Plot now picks range based on all plots, not just the last one
Fixes #3086
Fit some data, look at the plots
**Installers**
> 3086 weird plot auto scaling

- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
The changes related to multiplicity models (#2647) took a step too far and broke parameter updates for `structure_factor_mode` and other non-layer-parameter combo boxes. This removes an extra if statement that should not be reachable for the layer parameter. This might have a collateral effect on multiplicity models, though I couldn't find any.
Fixes #3014
Fixes #3053 (possibly)
Fixes #3108 (possibly)
Selected a P*S model and selected the beta approximation. The calculation generated the expected plots. Tested various features of multiplicity models to see if they still worked and did not notice anything off. Also tested the pinning of param values to 0.0 and that is, tangentially fixed.
**Documentation** (check at least …
> 3014: Beta approximation does not run

- src/sas/qtgui/MainWindow/GuiManager.py
Disables the orientation viewer menu item if running Wayland on Linux
Present on my windows machine, not present on @jamescrake-merani's Wayland machine
> 3114 orientation viewer doesnt clear itself on wayland

- .github/workflows/ci.yml
- build_tools/contributors.tsv
- src/sas/qtgui/MainWindow/GuiManager.py
- src/sas/qtgui/Perspectives/Fitting/FittingPerspective.py
- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
- src/sas/qtgui/Utilities/WhatsNew/WhatsNew.py
This is a series of changes that are needed for the final 6.0.0 release. Items changed in this PR:
- Added @jamescrake-merani to the contributors TSV list
- Cherry-picked https://github.com/SasView/sasview/pull/3090/commits/fb93303cd4767322ed883a14c6ea898b593918dd from #3090 
- Fixed the issue caused by fits going outside of the GSC model range. The calculated values were `NaN` which isn't plottable. (Note, this is a quick hack to access a sasdata class method that should really be its own function.)
- Moved to the release tags for SasData and SasModels to ensure frozen code.
- Fixed optimizer loading described in https://github.com/orgs/SasView/discussions/3116#discussioncomment-10906801
**ANY OTHER FIXES MAY GO HERE**
Refs https://github.com/orgs/SasView/discussions/3116
[if using the …
> 6.0.0: Final Fixes

- src/sas/qtgui/Plotting/Plotter.py
Fixes #3127 
Tested on Ubuntu. Haven't had a chance to test it on Mac but will do later.
**Installers**
> 3127 adding custom text to a graph causes it to go blank

- src/sas/qtgui/Perspectives/Fitting/GPUOptions.py
- src/sas/sascalc/fit/BumpsFitting.py
Any change to a preference was triggering an OpenCL environment reset, which was resulting in an OpenCL error when rerunning fits. This also fixes the tuple out of range issue noted by @wpotrzebowski in https://github.com/SasView/sasview/pull/3122#issuecomment-2414810923.
Fixes #3126
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
**Installers**
> 3126: Fix OpenCl and covariance issues

- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
- src/sas/qtgui/Utilities/DocViewWidget.py
This fixes the documentation issue noted by @wpotrzebowski in https://github.com/SasView/sasview/pull/3129#issuecomment-2425888386. The Mac rst files were all newer than the html files, which triggered the doc generation. Nothing (as of 11:52 EST 10/23) should trigger the documentation generation process at this point. If the files cannot be found, a 404 error will be shown instead of the documentation generation.
Tested using the installer from https://github.com/SasView/sasview/actions/runs/11465366459 and this fix seems to work.
> Release 6.0.0: Show 404 message instead of regen

- .github/workflows/ci.yml
- src/sas/sascalc/fit/BumpsFitting.py
This uses the new interface for bumps where every fit problem is multi-fit. Iterating through the models now directly returns the fitness object instead of the individual fit problem. This change brings SasView in line with this new behavior.
**This only fixes the majority of the issues related to this major change. Fits will continue to fail, but this PR allows the app to build and launch. See the issue for more info.**
Refs #3109
> 3109: Bumps FitProblem fix

- .github/workflows/ci.yml
- build_tools/requirements.txt
- src/sas/sascalc/fit/BumpsFitting.py
This updates the requirements file to use the latest versions of PySide6, numpy, and scipy, while locking bumps to versions less than 1. This also updates ci.yml to include these changes, and adds periodictable to the parallel repo list until another release is made with fixes for numpy compatibility.
Fixes #2857
Fixes #2897 
Fixes #2922
This is dependent on https://github.com/SasView/sasmodels/pull/613 and https://github.com/SasView/sasdata/pull/103 and will likely fail to build until they are merged.
Locally, all tests pass and I am able to run the program without issue.
**Installers**
> 2897, 2922: Use latest version of external (numpy, scipy, PySide) packages

- .github/workflows/ci.yml
Removing set of actions required for 6.0.0. Mac and Windows installers will still fail due to cert issues. 
#3167 
Checked CI and installed and quickly tested Mac installer
**Installers**
> Cleaning up ci.yml after release 6.0.0

- src/sas/qtgui/MainWindow/DataExplorer.py
- src/sas/qtgui/MainWindow/GuiManager.py
- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
I've tried to fix #3159 by changing the `deleteIntermediateTheoryPlotsByModelID` method so that it deletes by tab id, and not model id. This was causing the bug as we had 2 tabs with the same model, and it was trying to delete theory items from the other tab.
While this fixes the problem, I'm not entirely sure how suitable this fix is as I'm not aware of why this method was needed in the first place, and thus it could potentially break some other functionality. It would probably be useful to discuss this fix at the call. 
Followed the reproduction instructions Paul provided in #3159. I am no longer able to reproduce the bug in this pull request.
**Installers**
> Delete intermediate theory plots by tab id not model id.

- .github/workflows/ci.yml
Re enable the failing Ubuntu installer, and fix it by adding an extra dependency that was missing.
Fixes #3173 
CI tests now pass, specifically the Ubuntu installer test.
**Installers**
**Licencing**
> Renabling the Ubuntu installer test

- .github/workflows/ci.yml
This is a cherry-pick from #3164 to update the OSX notarization group ID. This should help the Mac builds get past the notarization step, but #3134 still applies so this step may still time out.
Tested as part of the previous PR and using the CI to see if the OSX builds are successful.
> Cherry pick of 3164 for release 6.0.1 - OSX Notarization

- .github/workflows/matrix.py
As decided at the contributor camp in Lund, we will only build macos-latest in the regular builds and the macOS-13 only for the release. 
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
**Installers**
> Removing macOS-13 from the regular build

- src/sas/qtgui/MainWindow/DataExplorer.py
For some reason, a commit seems to have been left out of #3160 which leads to an error whenever a plot is created. I think this may have been a mistake I made when cherry picking commits so I could rebase the branch onto release 6.0.1. I may have inadvertently left out the first commit.
Fixes #3159 
I have followed the reproduction steps mentioned in the original issue, and I am not able to reproduce the bug anymore.
**Documentation**
**Installers**
> Model ID Not Defined

- src/sas/qtgui/Plotting/Plotter.py
Fixes #3189 
Followed the reproduction steps in the issue, and the error no longer appears.
@butlerpd can you please confirm that the intended behaviour now occurs? If you run SasView from this branch, please ignore any errors with 'NameError: name 'model_id' is not defined'; I have fixed these in a separate PR.
**Installers**
> Fix calls to set_xticklabels and set_yticklabels

- src/sas/qtgui/MainWindow/DataExplorer.py
This fixes the issue of having two identical dataset entries in the data explorer, showing up on Data Freeze operation.
Fixes #3198
Locally on Win11
**Installers**
> removed superfluous signal connection.

- src/sas/qtgui/Utilities/GridPanel.py
- src/sas/qtgui/Utilities/UI/GridPanelUI.ui
Batch Fit Results table now has the option to open as a spreadsheet regardless of OS and opens to default system CSV viewer instead of only Excel. The button to do this is still labeled 'Open with Excel', though this would not be difficult to change - the only question is what to.
Fixes # 2868
Tested manually by opening a set of fit results on Mac and Linux. Confirmed that 'Open with Excel' button is visible and opens to default CSV viewer.
Have not tested whether this works on Windows, or that data is correct - though nothing about generating the csv to open has changed, so this should be fine. I just don't know how to get actual batch fit results.
**Installers**
> 2868 call the system default csv viewer not excel

- src/sas/cli.py
- src/sas/webfit/analyze/fitting/urls.py
- src/sas/webfit/analyze/fitting/views.py
- src/sas/webfit/analyze/models.py
- src/sas/webfit/data/models.py
- src/sas/webfit/data/views.py
- src/sas/webfit/serializers.py
- src/sas/webfit/settings.py
- src/sas/webfit/upload_example_data.py
- src/sas/webfit/urls.py
Made changes to settings.py in webfit to address errors in running the server and  user authentication. I suspect the issues were due to using Django version 5.1 when webfit was originally written using 4.2. Also changed a reference to the example_data directory to access it from sasdata rather than its original location in sasview, and fixed some minor spelling errors.
Successfully started webfit locally using python manage.py runserver.
**Installers**
> Start webfit

- src/sas/qtgui/Perspectives/Fitting/ConstraintWidget.py
- src/sas/qtgui/Perspectives/Fitting/FitThread.py
- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
Added guards against bad results returned by bumps in case fitting is canceled.
Fixes #3147
Local testing on win10
**Installers**
> foolproof the fitter against bump's antics

- .github/workflows/ci.yml
- build_tools/requirements.txt
This disables OpenCL during the sasmodels doc generation to allow the model figures to be generated under Windows.
Fixes #3211
CI
**Installers**
> 3211: Fix for sasmodel doc build

- .github/workflows/ci.yml
- .github/workflows/matrix.py
As discussed in an email exchange, Github are no longer going to be supporting their Ubuntu 20.04 runner image from 1st April. In my opinion, there is not much reason to build Ubuntu installers for this specific release. It is nearly 5 years old, and in May Ubuntu's 'standard support' for this version will end meaning further updates will require an Ubuntu Pro subscription. For users who, for whatever reason, cannot upgrade from Ubuntu 20.04, they can use the Flatpak to install SasView.
This branch also now tests the Ubuntu installer on 22.04 instead of 20.04.
After this PR is created, I'll check the CI to make sure we're not building any Ubuntu 20.04 installers. And of course check all the CI checks pass.
**Installers**
**Licencing** (untick if …
> Remove Ubuntu 20.04 from CI

- build_tools/requirements.txt
- src/sas/sascalc/fit/models.py
This remove the last reference to a logn obsolete Python2+3 compatibility layer
I plan to include this patch in Debian
https://wiki.debian.org/Python3-six-removal
> remove need for old "six" library

- src/sas/example_data/saved_states/fit_pr_and_invariant_project.svs
- src/sas/example_data/saved_states/test.inv
- src/sas/qtgui/MainWindow/UI/MainWindowUI.ui
- src/sas/qtgui/Perspectives/Fitting/media/fitting_help.rst
Removed the bookmark button, and some other references to it. As discussed in #3213 , it doesn't appear to be implemented.
Ran SasView. The bookmark button no longer appears. I tried loading the save states that used to contain a tag for it but from what I can understand, they are all in the old format anyway. I was getting errors but I don't think those were caused by this branch.
**Installers**
> Remove bookmark button

- src/sas/qtgui/MainWindow/GuiManager.py
- src/sas/qtgui/MainWindow/MainWindow.py
- src/sas/qtgui/Utilities/NewVersion/NewVersionAvailable.py
- src/sas/system/config/config.py
Adds a popup that appears at startup when there is a new version. Fulfils the requirements specified in #3209 
Tested as best I can without live testing from the web. Looks OK, possibly worth doing a live test though.
**Installers**
> 3209 new version available box

- src/sas/qtgui/MainWindow/DataExplorer.py
`Delete Data` button and `Delete` in the data item context menu differed in functionality, with the latter being buggy.
This PR fixes the issue by assigning the same slot to both actions.
Fixes #3234 #3235
Local Win10 
**Installers**
> Equalize behaviour of Delete actions.

- build_tools/requirements.txt
- installers/sasview.spec
Built binaries were having trouble compiling models ever since the change from tinycc to tccbox in sasmodels. This ensures developers testing the binaries are able to run fits.
Fixes #3250
**Installers**
> 3250: Replace tinycc with tccbox

- src/sas/sascalc/fit/BumpsFitting.py
In release 1.0.0b3, the class structure for `bumps.fitters.FitBase` changed so that the fit classes all have a `state` attribute, but it is `None` for all except `dream` and `de`.
The check in `sas.sascalc.fit.BumpsFitting` for fit results from `dream` is then broken without this PR, if using the most recent version of `bumps`.
I ran an `amoeba` fit with bumps==1.0.0b3 and got an error from this part of the code, as it tried to call `state.draw()` on the state from `SimplexFit`.
I made the change in this PR, and then was able to run both `amoeba` and `dream` fits, showing the results.
**Installers**
> Compatibility with bumps>=1.0.0b3

- src/sas/qtgui/Utilities/PlotView.py
- src/sas/qtgui/Utilities/ResultPanel.py
Summary: Use locally-defined FitResultView (QtWidget), no more import from bumps.gui or monkey-patching
Fixes #3252
Requires `bumps>=1.0.0b4` (for the plotting functions)
Also requires #3268 (for compatibility with latest bumps)
- all imports of wxPanel classes from `bumps.gui` (e.g. `bumps.gui.uncertainty_view.UncertaintyView`)
- monkey-patching of `bumps.gui.plot_view`
- including `_PlotViewShared` wrapper for mocking wxPanel from `sas.qtgui.Utilities.PlotView`
- `EmbeddedPylab` class; we are now using functions that can plot directly to the `FigureCanvas` provided
- imports of plotting functions directly from `bumps.dream.views` and `bumps.dream.var_plot`
- **parameter selector for "Parameter Trace" panel!**
Example: 
Labels and plot formatting changed for convergence plot, with more …
> Refactor bumps result views

- src/sas/qtgui/Calculators/Shape2SAS/Constraints.py
- src/sas/qtgui/Calculators/Shape2SAS/DesignWindow.py
This updates the Shape2SAS imports related to the model editors.
Fixes #3322
CI should now succeed for the Ubuntu builds
**Installers**
> 3322: Shape2SAS imports

- .github/workflows/ci.yml
The dmg file has a Mac release-specific name that wasn't accounted for in one of the test runners.
The MacOS CI succeeded in the push test. **The push test runner for Ubuntu should fail**, but the pull request test runner should succeed now that #3323 is merged into main.
> Fix MacOS Test Runner Issue

- src/sas/system/user.py
- src/sas/system/version.py
A minor bugfix and a small improvement to do with sasview version handling:
- The import of `_version` from the hatch-vcs automation was incorrect - trivial fix to bring it in. 
- The versioned directory for config/cache should be only dependent on the base version (x.y.z) component and not on development markers (alpha, beta, dev).
This PR is aimed against `release-6.1.0` branch but is also needed in `main`. Please let me know if duplicating the PR is desired to get this fix synced sooner rather than later.
`run.py`:
- check the version string in title bar and logs 
- check what directory it wants to use when run
**Installers**
> Improvements in sasview version handling - internal version and versioned directory

- .github/workflows/nightly-build.yml
Somewhere in the process of updating CI.yml, the tarball filename changed for the linux installer bundle. This PR updates the filename.
Fixes #3328 
CI - tarball found and uploaded
**Installers**
> Update tarball name in nightly flow to match CI.yml

- .github/workflows/nightly-build.yml
The nightly-build output contains updated installers but still contains the old source. The source is linked to the git tag `nightly-build` which is isn't changing, and so the source tarballs continue to point to wherever that tag pointed.
The approach here is to delete the release and the tag and recreate it, meaning that not only does the tarball get updated but the date for the release gets updated too, rather than remaining at some time in 2023.
(Note that this PR also contains the change from #3334 otherwise the CI can't pass; cross-fork CI is likely to fail with permissions issues)
Fixes #2648
CI https://github.com/llimeht/sasview/actions/runs/14773162725
**Installers** …
> Clean out nightly files

- docs/sphinx-docs/Makefile
- docs/sphinx-docs/extract-module-resource.py
- run.py
- src/sas/__pyinstaller/hook-sas.py
- src/sas/sascalc/doc_regen/makedocumentation.py
- src/sas/sascalc/doc_regen/regenmodel.py
- src/sas/sascalc/doc_regen/regentoc.py
Finding resources inside the module should be done with `importlib.resources` wherever possible, and not using file paths. Calculating locations using file paths fails when modules are inside zip files, wheels, manipulated by pyinstaller. The resources can even end up in different locations depending on the operating system and installation 'style' (all in one directory vs separate `/usr/bin` or `.../.venv/bin/` etc). 
The current code for locating the documentation makes incorrect assumptions about the proximity of the documentation files to the executable.
This PR adds code to obtain the documentation files firstly from the module using `importlib.resources` and then other locations as a fallback. 
Fixes # (I thought there were several bugs?)
This PR is needed in both the …
> Documentation viewer/regeneration, wheels, importlib.resources

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/pull_request_template.md
- Include information about how sasview was installed in the bug report template. It's useful to know if this is form a git checkout, the windows installer, pip install, etc.
- Include testing wheels as an installer route that can be checked in the course of testing a PR
(this should be in both `main` and `release-6.1.0` branches - let me know if you want a second PR for that)
n/a
**Installers**
> Update PR and Bug templates 

- .github/workflows/ci.yml
CI already knows not to try to sign/notarise the installers when running on push within a fork. This change ensures that the sign/notarise steps only happen when a PR comes from the `sasview/sasview.git` repository and not from a fork. This will suppress spurious errors about signing keys not being available in PRs.
Anyone using the unsigned installers likely needs to jump though additional hoops to enable the unsigned code, but they can't currently even get to the unsigned installers because the job fails prior to upload.
CI on this PR - it doesn't fail :)
(Checking that signing still works for 'internal' PRs is still needed)
**Installers**
> Suppress signature errors when CI run on PRs from forks

- src/sas/qtgui/Perspectives/Corfunc/CorfuncPerspective.py
This moves the isinstance check for data objects in Corfunc to after the data extraction step. Also updated the wording to so the Corfunc error says Corfunc, not Invariant.
Fixes #3359 
Tested locally using run.py
**Installers**
> 3359: Corfunc not accept Data1D

- src/sas/qtgui/Plotting/QRangeSlider.py
When a `LineConnector` is created for Q range sliders in a plot, use the connected inputs (e.g. min Q text input) to initialize the position of the slider.
Fixes #3347
I have tested in the local dev environment that this fixes #3347. I have tested that other perspectives with Q range sliders are not affected by this change. The same bug (Q range sliders reset to the Q range of the data on plot update) is present in the P(r) Inversion perspective, but it is unfortunately not fixed by this change.
**Installers**
> Q range sliders reset after fitting

- src/sas/qtgui/Perspectives/Fitting/ComplexConstraint.py
- src/sas/qtgui/Perspectives/Fitting/ConstraintWidget.py
- src/sas/qtgui/Perspectives/Fitting/UnitTesting/ComplexConstraintTest.py
- src/sas/qtgui/Perspectives/Fitting/UnitTesting/ConstraintWidgetTest.py
- src/sas/qtgui/Perspectives/Fitting/UnitTesting/FitPageTest.py
- src/sas/qtgui/Perspectives/Fitting/UnitTesting/FittingWidgetTest.py
- src/sas/sascalc/fit/BumpsFitting.py
Refactoring of the Fitting widget left some dangling references to old methods, which now reside on separate objects.
This got fixed.
Fixes #3343
Local Windows 10 tests
**Installers**
> Simultaneous fitting issues

- src/sas/qtgui/MainWindow/DataExplorer.py
- src/sas/qtgui/MainWindow/UnitTesting/DataExplorerTest.py
#3236 set the delete dataset action to a single method (there were two separate methods before, executed depending on the context). The unused method was left to make sure things don't break with the new setup.
They seem not to, so the additional, unused method has been removed now.
Fixes #3238 
Local Win10 dev build
**Installers**
> removed unused method, updated unit tests

- .github/workflows/nightly-build.yml
Wheels are now generated for sasview as part of the build process, and if prerelease versions of sasmodels, sasdata, and bumps are needed, these wheels are also generated. This PR publishes a zip of the wheels and the sasview sdist alongside the nightly builds of the other installers.
(This PR also contains the change from #3334 to allow the actions to pass)
CI of nightly - https://github.com/llimeht/sasview/releases/tag/nightly-build (CI on the PR is likely to fail due to lack of secrets to sign the installer at an earlier stage of the action; that's a separate bug to fix)
**Installers**
> Publish wheels along side other installers in nightly-builds action

- src/sas/qtgui/MainWindow/DataExplorer.py
- src/sas/qtgui/Perspectives/SizeDistribution/SizeDistributionLogic.py
- src/sas/qtgui/Plotting/PlotterData.py
This fixes the issue in #3276 by adding a new role, `DataRole.ROLE_SIZE_DISTRIBUTION` and making it an exception to the rule that ALL plots that are not standalone get plotted with the main data in the same chart.  In principle one could also try a direct call to `plotData` instead of `displayData` (assuming there is a sgnal for that which is unclear). This is what the `create New` graph button does for example but it is not clear that all the logic we want for these plots will work doing that?
in the process also fixed issue #3344 by adding an index to the for loop and only running the if statement for the first iteration.
Fixes #3276
Fixes #3344
Checked by running locally in dev environment and for 3344 tested with both Invariant and the new sizedistribution
[if using the editor, use …
> 3276 parent data needs to be removed from size distribution perspective results plot

- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
- src/sas/sascalc/fit/BumpsFitting.py
- src/sas/sascalc/fit/expression.py
Allows running constrained fits with new bumps version >= 1.0.0b6
Fixes #3370
Ran a test constraint fit with the fix, and it works without the error described in #3370 
**NOTE**: the convergence plot doesn't seem to work when running a consrtrained fit, which is I think a different issue.
**Installers**
> Fix bumps constrained fit

- src/sas/qtgui/MainWindow/MainWindow.py
Removed GPU rendering in the QtWebWidget, which was causing issues with some graphics cards on Win10.
Fixes #3384
Running docs in SasView installed from the installer.
**Installers**
> Fix for documentation window crashes

- src/sas/qtgui/Perspectives/SizeDistribution/SizeDistributionPerspective.py
- src/sas/qtgui/Perspectives/SizeDistribution/UI/SizeDistributionUI.ui
This changes the output box to show labels and empty text boxes for the outputs so that users can see what the expected output is.
Fixes #3392
Tested that the output text boxes are populated after a successful fit and that they are reset to empty when data is deleted.
**Installers**
> Add text boxes to size distribution output box and add/fix units

- .github/workflows/ci.yml
As noted in #3383 by @rozyczko, the windows installer artifact also contains a tarball of the files prior to going into the installer. This wasn't intended - it's just one of the perverse things than happens in case-insensitive file systems. It's easy to fix by getting rid of the globs and making the filenames more specific.
CI
**Installers**
> Deduplicate the windows installer artifact

- src/sas/qtgui/Plotting/Plotter.py
This is a second attempt at fixing the problem reported in #3197. As discussed in PR #3386 comments, it turns out that using the log formatter should automatically take care of the issue with the tick labels on log scale. It also turns out that the linear scale has a similar problem. This is fixed by using the scaler formatter as in PR #3386.
This is a much simpler fix that implemented in PR #3386. It just adds the tick label formatting to the `onCustomizeLabel` method.
Fixes #3197
tested in the local dev environment of windows 10 machine. tried both x and y, both linear and log scales.
**Installers**
> Second try at fixing custom labels

- .github/workflows/ci.yml
The [uv tools](https://docs.astral.sh/uv/) are reimplementations of various Python package management tools in rust - they are between 10 and 100× faster for many operations. 
`uv` has lots of features and we might explore some of them later; @jamescrake-merani might like `uv lock` and `uv sync` for managing the dependency list, for example.
For the moment though, this PR is only looking at using `uv` as a pip-compatible package installer. It downloads and installs the wheels from pypi in exactly the same way as we are used to with `pip`, except it takes 3-5 s rather than 1-3 min (this time is quite variable).
Across the whole CI run, this shaves approx 2-4 min off CI with uv's faster dependency resolver and unpacking of wheels.
CI
[if using the editor, use `[x]` in place of `[ ]` to …
> Speed up CI - faster python module installation with uv

- src/sas/qtgui/Utilities/ModelEditors/TabbedEditor/PluginDefinition.py
This ensures the python model creation check box is selected anytime the model name given does not already exist.
Fixes #3378
**Installers**
> 3378: Ensure python model is selected when window opens

- src/sas/qtgui/Calculators/Shape2SAS/UI/DesignWindowUI.ui
This replaces a few fixed size spacers in the Shape2SAS SAXS UI file with expanding elements to ensure the input labels are always visible.
Fixes #3408
Tested locally to be sure the UI is responsive to different sizes in both vertical and horizontal stretching.
**Installers**
> 3408: Shape2SAS SAXS UI label visibility

- src/sas/qtgui/Calculators/Shape2SAS/ViewerModel.py
This fixes the issue related to the 3D plot in the Shape2SAS window where spheres looked liked ellipsoids. I also added a few tweaks to the plots, mostly to allow them to expand as the window is expanded.
Fixes #3309
Locally, the aspect ratios for all of the 3D plot axis remains the same.
**Installers**
> 3309: Shape2SAS plotting enhancements

- src/sas/qtgui/Perspectives/SizeDistribution/SizeDistributionLogic.py
- src/sas/qtgui/Perspectives/SizeDistribution/SizeDistributionPerspective.py
- src/sas/qtgui/Perspectives/SizeDistribution/UI/SizeDistributionUI.ui
- src/sas/sascalc/size_distribution/SizeDistribution.py
Enable in the GUI fitting of the power in the power law background estimation.
Fixes #3279
Tested locally with `src/sas/sascalc/size_distribution/test_data/Alumina_usaxs_irena_input.csv`.
**Installers**
> Power law background estimation in Size Distribution

- src/sas/sascalc/size_distribution/SizeDistribution.py
The error multiplier now multiplies the error bar rather than divide. The warnings have been updated to reflect the change. Also cleaned up some debugging print statements.
as described above. 
Fixes #3391 
tested locally in dev environment on windows. tried out all combos of weight types with standard data and a data set with no error bars. There are bugs discovered when running the later which are not part of this PR but will be turned into a new issue.  The values of the weights and the sigma were verified under several conditions using print statements and a calculator. 
**Installers**
> Fix error multiplier

- src/sas/qtgui/Perspectives/SizeDistribution/SizeDistributionLogic.py
- src/sas/qtgui/Perspectives/SizeDistribution/SizeDistributionPerspective.py
Enabling of the dI radio button checkbox 2 was moved from `enableButtons` and `setupWindow` to `setData` and which radio button is checked by default was added there. Those defaults depend on whether or not the new data set has dy or not and should not be changed every time a fit or other action is performed (besides loading new data), nor should they be set permanently at the start.
Also fixed a bug in logic where di_flag was not getting reset once set to "True". This could have been done in the main perspective on cleanup between data sets  (in `resetWindow`), but it seemed more general to fix at the source?
Fixes #3422 
Tested in the local environment on windows 10. Loaded both a the irena test data set (which contains dy) and the `cyl_400_20.txt` example data set (which does not …
> 3422 default weighting for size distribution should be i if data has no dy

- src/sas/qtgui/Plotting/Binder.py
This removes warnings when mousing over plots (for certain platforms and OS?)
This PR does two things, in the handler that checks if a mouse event is contained within an artist:
1. checks if mouse event is associated with _any_ axes before trying to determine if an artist contains it (`event.inaxes is not None`)
2. if the first check passes, check if the axes associated with an event match the axes associated with the artist before running `artist.contains()`
Fixes #3145
Warnings appear when mousing over fit plot before fix.  They are gone after fix.
**Installers**
> Fix mousemove warning in matplotlib plots

- src/sas/qtgui/Perspectives/SizeDistribution/SizeDistributionPerspective.py
- src/sas/sascalc/size_distribution/maxEnt_method.py
This changes the maximum entropy method to return the chi2 normalized by the number of bins. The style of the convergence message is changed to red and bold if the fit returned is not converged.
Fixes #3410
Tested locally what the message looks like with and without converged results. The converged results now has chi^2 close to 1.
**Installers**
> Size distribution should report normalized chi^2

- src/sas/qtgui/Calculators/Shape2SAS/Constraints.py
- src/sas/qtgui/Calculators/Shape2SAS/DesignWindow.py
- src/sas/qtgui/Calculators/Shape2SAS/Tables/subunitTable.py
- src/sas/qtgui/Calculators/Shape2SAS/ViewerModel.py
This PR replaces #3444. It fixes the same issues as the previous PR, but removes some of the original changes that were in question.
Fixes https://github.com/SasView/sasview/issues/3413 - When a column or series of columns is selected, the first column in the selection is set as the one to be deleted.
Fixes https://github.com/SasView/sasview/issues/3441 - If one or more shapes are completely within other shapes and overlap is excluded, errors are no longer thrown.
Fixes https://github.com/SasView/sasview/issues/3442 - A couple of typos are fixed in the tool.
No issue - Fixes an issue with the hollow sphere where certain parameters were not being calculated.
**Installers**
> Shape2SAS outstanding issues redux

- .github/workflows/ci.yml
Two issues were spotted in the 6.1.0b1 builds:
- the pinned versions of the dependencies were not installed in the CI build for the tag
- the generated package had an ugly version string (`6.1.0b2.dev0+gd5f5c0082.d20250603` rather than `6.1.0b1`)
Unpacking this version string, it's a development version that would be leading towards `6.1.0b2` that is currently `0` commits past the previous tag, it is at the expected git hash (`d5f5c0082`), with an uncommitted modification that was spotted on that date (`20250603`). The cause of this ugly version string is that git tracked files were modified during build which the versioning then spots and tracks in the string — that's the perfect version string for a regular CI build, but a terrible version string for a release. 
The changes here:
- …
> Fix version strings in release-branch builds

- src/sas/qtgui/Utilities/MuMag/MuMag.py
Changed the `onHelp` call from a webbrowser call to a non-existent sasview.org webpage to the standard help page within the internal documents using the `GuiManager.showHelp` method 
Fixes #3452 
Checked on the dev environment of windows 10 machine. Prior to change a 404 as with installer, after the fix the proper page comes up
**Installers**
> 3452 mumag help button doesn't

- src/sas/__pyinstaller/hook-sas.py
pyinstaller needs to be told what files to bundle with the module - this PR adds some more files to what pyinstaller will keep with the `sas` module.
Fixes #3455
Checked file list from pyinstaller output from CI. Installers not otherwise tested - those with the right hardware need to do that!
**Installers**
> Extend pyinstaller data for sas module to include all of sphinx output

- src/sas/qtgui/Utilities/MuMag/MuMag.py
- src/sas/sascalc/size_distribution/maxEnt_method.py
As a regression on #3163, 4 new SyntaxWarning have appeared:
```
$ find -name \*pyc -delete; py3compile ./src
.../src/sas/qtgui/Utilities/MuMag/MuMag.py:235: SyntaxWarning: invalid escape sequence '\c'
self.chi_squared_axes.set_ylabel('$\chi^2$')
.../src/sas/qtgui/Utilities/MuMag/MuMag.py:243: SyntaxWarning: invalid escape sequence '\m'
self.residual_axes.set_ylabel('$I_{\mathrm{res}}$')
.../src/sas/sascalc/size_distribution/maxEnt_method.py:134: SyntaxWarning: invalid escape sequence '\c'
target $\chi^2$ and to move beta one step closer towards the solution
.../src/sas/sascalc/size_distribution/maxEnt_method.py:185: SyntaxWarning: invalid escape sequence '\D'
I_{Q}=|\Delta\rho^2|\int|F(Q,r)^2|(V(r))^2N_{P}(r)dr
```
None needed
[if using the editor, use `[x]` in place of `[ ]` to check a …
> Fix newly appeared SyntaxWarnings

- .github/workflows/ci.yml
Replaced Lando action with official digicert action "digicert/ssm-code-signing"
Fixes #3231
Installer from the github build checked for presence of "Digital Signatures" tab.
**Installers**
> Fixed windows binary signing action

- build_tools/release_automation.py
There are two main changes
- The script now uses the Python `csv` module, rather than parsing the `tsv` file manually. This means that quotations in the file will be handled properly.
- Some of the script broke on Linux (and presumably on macOS as well) because of how Unix file systems are case sensitive, as opposed to the Windows file system which is case insensitive. I've fixed this.
I ran the script, and pretty printed the contributors dictionary which came out as expected. I haven't tested the upload to Zenodo, however.=
**Installers**
> Updates to the release automation script

- pyproject.toml
This raises the minimum Python version to Python 3.11. This is what we have been testing on for the release, so it makes sense to specify this in the `pyproject.toml` as well.
As per discussion in #3498
I haven't had a chance to, but presumably it should fail to install on Python versions < 3.11.
**Documentation**
**Installers**
**Licensing**
> Specify a requirement of at least Python 3.11 in the pyproject.toml 

- .github/workflows/ci.yml
A merge conflict between the release branch and main branch wasn't resolved correctly. This combines elements from both branches, as I believe they were expected.
> Use requirements-dev.txt instead of list of dependencies

- .github/workflows/ci.yml
- .gitignore
The CI has been modified to run the ruff linter using the default ruleset. If the linter detects any changes which it is able to fix automatically, the CI is stopped for that commit, and a new commit from "pre-commit" is added which contains the ruff fixes, and the CI then run on that commit. If the ruff linter detects changes it cannot automatically fix, they are ignored.
These changes to the CI require the installation of "pre-commit lite" on this repository. I have already requested this.
Fixes #3498 
I have filed pull requests on my own fork of SasView. See: https://github.com/DrPaulSharp/sasview-test/pull/11
**Installers**
> Adds ability to automatically apply ruff linting fixes to CI

- src/sas/qtgui/Calculators/DensityPanel.py
- src/sas/qtgui/Calculators/GenericScatteringCalculator.py
- src/sas/qtgui/Calculators/KiessigPanel.py
- src/sas/qtgui/Calculators/SldPanel.py
- src/sas/qtgui/Calculators/SlitSizeCalculator.py
- src/sas/qtgui/MainWindow/DroppableDataLoadWidget.py
- src/sas/qtgui/MainWindow/MainWindow.py
- src/sas/qtgui/Perspectives/ParticleEditor/CodeToolBar.py
- src/sas/qtgui/Plotting/BoxSum.py
- src/sas/qtgui/Plotting/ColorMap.py
- src/sas/qtgui/Plotting/MaskEditor.py
- src/sas/qtgui/Plotting/ScaleProperties.py
- src/sas/qtgui/Plotting/SetGraphRange.py
In #3507, a number of import statements referring to UI components were automatically removed as they are not explicitly referred to in the code. However, they are required for the GUI to function properly, as shown in #3551. I have restored all of the import statements that were removed. Note that the accompanying comment `# noqa: F401`  prevents ruff from applying the unused import fix to this line.
Fixes #3551
I have followed the reproduction steps in #3551 and seen that the icons are restored.
**Installers**
> Restores UI import statements

- .github/workflows/ci.yml
`libausaxs` should now be present and included in the installers. 
Fixes #3545, needed for #3544
The Linux installer has been tested and verified to now include `libausaxs`. The issue was that `libausaxs` was previously only being downloaded for test builds, but not for the installers, which were therefore created without it. As functionality was already verified in #2882 and tests are still passing (including the `libausaxs` test), I don't think we have to do anything further here. 
**Installers**
> Ensure libausaxs is downloaded when building installers

- src/sas/sascalc/invariant/invariant.py
Running the calculation unit tests locally gave a set of warnings:
> =============================== warnings summary ===============================
test/sasinvariant/utest_data_handling.py: 26 warnings
test/sasinvariant/utest_use_cases.py: 13 warnings
/home/runner/work/sasview/sasview/src/sas/sascalc/invariant/invariant.py:363: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
err_matrix = math.fabs(residuals) * cov
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
One CI example that shows the warnings: https://github.com/SasView/sasview/actions/runs/16317859941/job/46088019662
These warnings are …
> Fix Invariant Test Warnings

- build_tools/requirements.txt
- src/sas/qtgui/MainWindow/GuiManager.py
- src/sas/qtgui/Utilities/NewVersion/NewVersionAvailable.py
This PR aims to fix #3420 by removing our reliance on the `ConnectionProxy` class, and instead use the `get` request function from the `requests` library.
Tested on `run.py`, and the wheel. Unfortunately, I haven't been able to test on the installer as I'm not sure if there is a way to fake the version to an older one to test the popup menu. Does anyone know how to do this? It might be useful if we add a debug version override flag for this purpose.
**Installers**
> Replace usage of connection proxy with the requests library.

- src/sas/qtgui/Utilities/GridPanel.py
This fixes an issue introduced in v6.1.0 in PR #3137. The batch fitting window would no longer open due to different data structure between the batch P(r) results and batch Fitting results. The P(r) functionality was moved to the `BatchInversionOutputPanel` class and the original functionality was restored for the batch fitting.
Despite the code freeze, I think this fix should be implemented for v6.1.1 due to the importance of the batch results window.
Fixes #3543
Loaded AOT core and AOT shell files. Sent both to batch fitting and batch P(r). Tested fits and plotting from the results panel and everything worked for both batch fitting methods.
**Installers**
> 3543: Fix batch fit results display and plotting

- build_tools/contributors.tsv
- build_tools/release_automation.py
There is an ongoing discussion as to how authors should be ordered in Zenodo:
https://github.com/orgs/SasView/discussions/3503
While this discussion is ongoing, an agreement was reached at the last fortnightly meetings that the release manager's name should come first, and then everyone else's should be in alphabetical order. This PR makes the necessary changes to the release automation script for this to be done.
A new column 'ReleaseManager' has been added to the `contributors.tsv` file, with my name currently marked with an 'x' only.
I pretty printed the contributors list, and the list is in the order I expected
**Note for reviewer:** It would be great for this to be independently verified.
**Installers**
> Adapt release automation for new author ordering

- src/sas/qtgui/Perspectives/Fitting/AssociatedComboBox.py
- src/sas/qtgui/Perspectives/Fitting/FittingUtilities.py
- src/sas/qtgui/Plotting/QRangeSlider.py
- src/sas/sascalc/doc_regen/regenmodel.py
- src/sas/sascalc/fit/models.py
I have converted type comments in the codebase to type hints, as discussed in #3170. I used the tool [com2ann](https://github.com/ilevkivskyi/com2ann) for the initial conversion before a bit of tidying up.
The code builds correctly and the tests pass.
**Installers**
> Converts type comments to type hints

- installers/sasview.spec
This ensures the `example_data` directory is in the base installation directory to match the tutorials
Fixes #3577
Downloaded the installer and tested locally on Windows.
[**Documentation** (check at least one)
**Installers**
> 3577: Example data directory at base installation directory

- src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
- src/sas/qtgui/Perspectives/Fitting/PolydispersityWidget.py
This fixes an issue introduced in v6.1.0 with the polydispersity params not updating in the fit tab after they are updated on the PD tab. The method to do this was inadvertently removed during the fitting refactor.
Fixes #3576
From source, I tested both the sphere and cylinder models, and saw, as the PD width and PD function change, the child values for the fit page also change to match.
**Installers**
> 3576: Fix polydispersity values shown in fit params tab

- .github/workflows/ci.yml
This is needed for the release due to a recent change in a dependent library (that isn't getting pinned...).
> Release 6.1.1: include libcairo-2 in Ubuntu library installation list

- src/sas/qtgui/Perspectives/Invariant/InvariantPerspective.py
Previous PR #3627 changing the Invariant perspective files removed the param `model` from the definition for `update_details_widget`, but it was left behind in a call. This PR fixes that.
Ran the Invariant perspective.
**Installers**
> Removes redundant param
