src/sas/sasgui/perspectives/invariant/invariant_panel.py, src/sas/sasgui/perspectives/invariant/invariant_state.py
I didn't want to push directly to master since I'm not sure where we stand with regards to the 4.0 beta release, so thought it made sense to issue a pull request
=> Load invariant state correctly (fixes #615)

src/sas/sascalc/dataloader/readers/anton_paar_saxs_reader.py, src/sas/sascalc/dataloader/readers/xml_reader.py
For after 4.0 is released, here is a final version of the SAXSESS reader.
=> #500: Final changes to Anton Paar SAXSESS reader.

src/sas/sascalc/data_util/qsmearing.py, src/sas/sascalc/dataloader/data_info.py, src/sas/sascalc/dataloader/readers/sesans_reader.py, src/sas/sascalc/fit/AbstractFitEngine.py, src/sas/sascalc/fit/BumpsFitting.py, src/sas/sasgui/guiframe/dataFitting.py, src/sas/sasgui/guiframe/data_manager.py, src/sas/sasgui/perspectives/fitting/basepage.py, src/sas/sasgui/perspectives/fitting/fitpage.py, src/sas/sasgui/plottools/plottables.py
=> Revert "Jurtest2"

setup.py
This also fixes a previously unnoticed issue where the rst files for the pr perspective were not included in the build file.
=> ticket-855: Modify setup.py to include file_converter and corfunc in Jenkins build.

sasview/README.txt
I took a stab at writing the release notes for the upcoming release. I'm not sure how complete these are.
=> Release Notes for 4.1 release

sasview/local_config.py
Have added new DOI and edited requested acknowledgement to only refer to funding bodies.
=> Updating local config with DOI etc

setup.py, src/sas/sascalc/dataloader/readers/cansas_reader.py, src/sas/sasgui/perspectives/fitting/pagestate.py
This fixes the two save state issues regarding a bad relative import and saving transmission spectrum data. Also, all of the test data folders are now added to the build script.
=> Release: Save state and test data

src/sas/sasgui/perspectives/fitting/fitting.py
Don't add P(q) and S(q) to the data manager since we can't get access to those models with updated parameters.
=> Fixes #741 Remove P(Q), S(Q) feature

mac_setup_homebrew.sh
* Rename to 'mac_setup_homebrew.sh'
=> Add OSX Build Instructions

.travis.yml, build_tools/travis_build.sh
See #47. I intended to reopen that but I force pushed to one of my branches, meaning I couldn't reopen the PR...
=> TST: fix travis, use conda

docs/sphinx-docs/build_sphinx.py, setup.py
Build docs with single command 'python setup.py docs'
=> Ticket 555

check_packages.py
=> Don't check pywin version in check_packages: it may not be marked in the file

src/sas/sascalc/pr/c_extensions/Cinvertor.c, src/sas/sascalc/pr/c_extensions/invertor.c, src/sas/sascalc/pr/c_extensions/invertor.h, src/sas/sascalc/pr/invertor.py, src/sas/sasgui/perspectives/calculator/model_editor.py, src/sas/sasgui/perspectives/calculator/pyconsole.py, src/sas/sasgui/perspectives/fitting/fitting.py, src/sas/sasgui/perspectives/fitting/models.py, src/sas/sasgui/perspectives/pr/inversion_panel.py, src/sas/sasgui/perspectives/pr/inversion_state.py, src/sas/sasgui/perspectives/pr/media/pr_help.rst, src/sas/sasgui/perspectives/pr/pr.py, test/pr_inversion/test/utest_invertor.py
When creating a custom model, if the line defining a fitting parameter ends in a comment, it is now handled correctly. This closes ticket [#864
](http://trac.sasview.org/ticket/864)
Added an option to allow the user to manually input a background value in the Pr perspective. This closes ticket [#648](http://trac.sasview.org/ticket/648)
=> Bug Fixes and Improvements

src/examples/test_panel2D.py, src/sas/sascalc/calculator/instrument.py, src/sas/sascalc/dataloader/file_reader_base_class.py, src/sas/sascalc/file_converter/otoko_loader.py, src/sas/sascalc/fit/AbstractFitEngine.py, src/sas/sascalc/pr/c_extensions/Cinvertor.c, src/sas/sascalc/pr/fit/AbstractFitEngine.py, src/sas/sasgui/guiframe/data_processor.py, src/sas/sasgui/guiframe/events.py, src/sas/sasgui/guiframe/local_perspectives/data_loader/data_loader.py, src/sas/sasgui/guiframe/local_perspectives/plotting/binder.py, src/sas/sasgui/guiframe/local_perspectives/plotting/boxSlicer.py, src/sas/sasgui/guiframe/local_perspectives/plotting/masking.py, src/sas/sasgui/guiframe/plugin_base.py, src/sas/sasgui/guiframe/proxy.py, src/sas/sasgui/perspectives/calculator/gen_scatter_panel.py, src/sas/sasgui/perspectives/calculator/resolcal_thread.py, src/sas/sasgui/perspectives/fitting/fitproblem.py, src/sas/sasgui/perspectives/fitting/fitting.py, src/sas/sasgui/perspectives/fitting/fitting_widgets.py, src/sas/sasgui/perspectives/fitting/gpu_options.py, src/sas/sasgui/perspectives/fitting/simfitpage.py, src/sas/sasgui/perspectives/invariant/invariant_details.py, src/sas/sasgui/perspectives/pr/explore_dialog.py, src/sas/sasgui/plottools/binder.py, src/sas/sasgui/plottools/toolbar.py, src/sas/sasview/sasview.py
One of Debian's QA tools (`lintian`) runs a checker for common typos and spotted this one: 
> distrubution
=> Fix typo in P(r) peaks description

installers/installer_generator.py
Added explicit 64 bit installer directives to the INNO script generator
=> ticket 993

docs/sphinx-docs/source/conf.py, src/sas/sasgui/perspectives/calculator/media/resolution_calculator_help.rst, src/sas/sasgui/perspectives/calculator/media/sas_calculator_help.rst, src/sas/sasgui/perspectives/corfunc/media/corfunc_help.rst
Ignore the branch name.  This fixes 977 and not 997.
=> Remove all instances of \text from the repo (Ticket #977)

src/sas/sasview/sasview.py
Simple check for cc compiler added to sasview start-up. I've opened this pull request for testing purposes. To be reviewed after testing.
=> Checking cc compiler on OSX prior to sasmodel installation

src/sas/qtgui/MainWindow/DataExplorer.py, src/sas/qtgui/Perspectives/Fitting/FittingUtilities.py, src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
Solves SASVIEW-1035 and trac ticket 17
=> plot polydispersity

src/sas/sasgui/guiframe/local_perspectives/data_loader/data_loader.py
This is a cherry pick from ticket-1111.
=> Continue loading data files if a single file cannot be loaded.

src/sas/sasgui/perspectives/fitting/gpu_options.py
sasmodels.kernelcl now allows you to change the gpu device without reloading the module
=> gpu options panel uses improved sasmodels interface

src/sas/sascalc/dataloader/file_reader_base_class.py
Fixed bug in `sas/sascalc/dataloader/file_reader_base_class.py`
=> ticket #1212 fixed the qx.data bug

src/sas/sasgui/perspectives/fitting/gpu_options.py
See [ticket #1015](http://trac.sasview.org/ticket/1015).
Must have corresponding sasmodels PR applied.
=> Ticket 1015.  Clean out existing kernels when changing compute engine

src/sas/sasgui/perspectives/calculator/model_editor.py
Trac #1218
Copy of what is already in the ESS_GUI branch.
Added '\n' to import statements in the plugin model template text.
=> Added newlines to import statements in the plugin model template.

src/sas/_config.py, src/sas/sasgui/guiframe/gui_manager.py
Having problem with a mac not allowing custom_config.py to be overwritten, and so our failure paths were not checked.
Redo handling of failed custom config.
=> redo handling of cust config failures

src/sas/sasgui/plottools/PlotPanel.py
Figuring out proper handling of zmin_2D and zmax_2D will require more work.  
They do not appear to be settable by the user, so using the default should be fine, which is what this patch does.  However, it has not been checked against all uses of 2D plotting.
=> fix 2D log-scale plotting range when data contains zeros and negative values

src/sas/qtgui/Plotting/Plotter.py
I've adjusted the replacePlot function to always read the old axes styles on the plot before updating to the new values.  This seems to have solved the issue mentioned in the task.
=> Sasview 1127

src/sas/qtgui/Perspectives/Fitting/FittingUtilities.py, src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
- same approach as for 1D
- identical code for both cases moved into internal helper method
- renamed polydispersity Y axis to 'probability' as suggested
- attempt to close/finish SASVIEW-1035 and trac ticket 17
- https://jira.esss.lu.se/browse/SASVIEW-1035
- http://trac.sasview.org/ticket/17
=> show a polydispersity plot for 2D data as well

src/sas/qtgui/Perspectives/Fitting/GPUOptions.py
OpenCl driver information wasn't available when running tests. These commit should fix it in 5.0. Progress bar will be implemented separately.
=> Opencl drivier update when running Test 

docs/sphinx-docs/source/user/RELEASE.rst, src/sas/sascalc/dataloader/data_info.py, src/sas/sascalc/dataloader/readers/cansas_reader.py, src/sas/sasgui/guiframe/gui_manager.py, src/sas/sasgui/guiframe/gui_statusbar.py, src/sas/sasgui/guiframe/local_perspectives/plotting/plotting.py, src/sas/sasgui/perspectives/fitting/fitpage.py, src/sas/sasview/__init__.py
New 4.2.2 release candidate branched directly from 4.2.1 tagged release.
***DO NOT MERGE***
Old release candidate in branch release-4.2.2 included changes to master since release, and should be ignored.
Includes new zenodo tag that was created for the release-4.2.2 branch. Don't know how to redirect it to the end of this branch.
=> Release 4.2.2b

src/sas/sascalc/corfunc/transform_thread.py
Keep sascalc in sync with Qt GUI.
=> backport fix for corfunc plotting problem

src/sas/sascalc/dataloader/readers/red2d_reader.py
I cherry picked the lone commit for PR #1356 into ESS_GUI. This PR should be merged once the original one is approved to keep be sure sascalc remains the same during the transition from 4.x to 5.x.
=> ESS_GUI: Load in Mask Data column from NCNR 2D data.

src/sas/qtgui/Calculators/DataOperationUtilityPanel.py, src/sas/qtgui/MainWindow/DataExplorer.py, src/sas/qtgui/MainWindow/GuiManager.py
Minor fix for the data operations widget. All Data1D/Data2D plots from the Data Explorer now populate the comboboxes, as in 4.x
Fixes #1374
=> Ess gui data operations 1374

build_tools/conda_qt5_win.yml, build_tools/conda_qt5_win_commercial.yml, src/sas/qtgui/Calculators/DataOperationUtilityPanel.py, src/sas/qtgui/MainWindow/DataExplorer.py, src/sas/qtgui/MainWindow/GuiManager.py, src/sas/qtgui/Perspectives/Fitting/FittingWidget.py, src/sas/qtgui/Perspectives/Fitting/GPUOptions.py, src/sas/qtgui/Perspectives/Fitting/SmearingWidget.py, src/sas/qtgui/Perspectives/Invariant/InvariantPerspective.py, src/sas/qtgui/Plotting/Plotter.py, src/sas/qtgui/Plotting/Plotter2D.py, src/sas/qtgui/Plotting/Slicers/AnnulusSlicer.py, src/sas/qtgui/Plotting/Slicers/BoxSlicer.py, src/sas/qtgui/Plotting/Slicers/BoxSum.py, src/sas/qtgui/Plotting/Slicers/SectorSlicer.py, src/sas/qtgui/Plotting/UnitTesting/ColorMapTest.py, src/sas/qtgui/Plotting/UnitTesting/Plotter2DTest.py, src/sas/qtgui/Plotting/UnitTesting/PlotterTest.py, src/sas/qtgui/Utilities/GuiUtils.py, src/sas/sascalc/dataloader/data_info.py, src/sas/sascalc/dataloader/readers/red2d_reader.py
Addresses #1361 and #1350 among other minor plotting issues.
=> Ess gui plotting issues

test/pr_inversion/test/utest_invertor.py
Prevents lots of ResourceWarning noise from the test suite.
=> Ensure files are closed in test suite

src/sas/qtgui/Calculators/GenericScatteringCalculator.py, src/sas/qtgui/Calculators/UI/GenericScatteringCalculator.ui
This pull request addresses #1424 and these are minor fixes
1. Tool tip's been fixed (pdf -> pdb)
2. List of supported files has been extended (only omf before).
=> Ess gui generic scattering calc fixes

src/sas/sascalc/fit/models.py
=> 4.x support unicode in error messages from broken plugin models

src/sas/sasgui/perspectives/invariant/media/invariant_help.rst
I have rather significantly revised invariant_help.rst
Do you approve?
=> Issue1434 invariant documentation

src/sas/qtgui/Perspectives/Fitting/FittingWidget.py, src/sas/qtgui/Perspectives/Inversion/DMaxExplorerWidget.py
Converts float number of steps to integer number of steps for linspace for #1463.
I didn't test that it fixed the problem.
=> Ticket #1463 - linspace errors

src/sas/qtgui/MainWindow/DataExplorer.py
plotting of single data/multiple fit tab charts. #1454
=> Fix for Fit Panel based Plot command for single-data/multiple fit tab

src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
load reparameterised models properly. SASMODELS #381
=> Changed order of parameter assignment to allow reparameterized models to

check_packages.py
This is the same work done in #1482 but against ESS_GUI rather than master. The only difference are the yaml files I'm pointing to. I used the strictest yamls, rather than the 'min' versions.
=> 5.x: Check packages comparison to YAML files

docs/sphinx-docs/source/user/menu_bar.rst
Minor doc change/update to list the new menu items after changes to #1480
=> Ess gui 1480 docs

src/sas/qtgui/Perspectives/Corfunc/CorfuncPerspective.py, src/sas/qtgui/Perspectives/Corfunc/UI/CorfuncPanel.ui
This PR should handle #1413 
The primary complaint was the sluggishness of the Corfunc panel.  Looking through, panel was replotting the data every time the model changed.  Since the model had many parameters that were set sequentially, this caused several needless replots in a row.  The code now only plots when the model has been finalised and is noticeably snappier.
There has also been some tidying of the GUI.  The IDF hsa been removed and the Extract Parameters button has been re-instated.  The buttons have also been moved into a more logical grouping, as seen below.  (Ignore the idiosyncratic colour scheme)
=> Ticket1413 corfunc

build_tools/conda_qt5_win_commercial.yml, src/sas/qtgui/Utilities/IPythonWidget.py
Modified dependencies and code to re-enable python console for Windows.
=> Ess gui test ipython

build_tools/conda_qt5_win_commercial.yml
Quick fix for conflict merge after large PR merge.
=> Fix merge conflict in the windows YML file

build_tools/generate_zenodo_record.py, docs/sphinx-docs/source/user/RELEASE.rst, src/sas/qtgui/MainWindow/UI/AcknowledgementsUI.ui, src/sas/sasview/__init__.py
PR for 5.0.2 release candidate
=> Ess gui 5.0.2 release

build_tools/conda_qt5_win_commercial.yml
=> TEST PR DONT REVIEW/MERGE

src/sas/sascalc/dataloader/data_info.py, src/sas/sascalc/dataloader/readers/cansas_reader_HDF5.py, src/sas/sascalc/file_converter/nxcansas_writer.py, test/fileconverter/test/utest_nxcansas_writer.py
As outlined in https://github.com/nexusformat/definitions/issues/765, the NXcanSAS definition is changing and the version number is being incremented. This PR should capture those changes.
This PR is specific to 4.x. PR #1531 is the same content for 5.x.
refs #1527
=> Update reader and writer for NXcanSAS v1.1 changes (4.x)

src/sas/sascalc/dataloader/data_info.py, src/sas/sascalc/dataloader/readers/cansas_reader_HDF5.py, src/sas/sascalc/file_converter/nxcansas_writer.py, test/fileconverter/test/utest_nxcansas_writer.py
This is a parallel PR for #1530 pointing to the ESS_GUI branch instead of master.
refs #1527
=> Update reader and writer for NXcanSAS v1.1 changes (v5.x)

src/sas/qtgui/Perspectives/Fitting/ComplexConstraint.py, src/sas/qtgui/Perspectives/Fitting/ConstraintWidget.py, src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
Changes the user experience when  using constraint. See #1490.
=> Ess gui 1490 constraints

src/sas/qtgui/Perspectives/Fitting/ReportPageLogic.py
When generating a fit report, the SasView version, sasmodels version, bumps optimizer, and functions used for polydispersity are now included in the dialog.
fixes #1564
=> (ESS_GUI) Report dialog enhancements

src/sas/qtgui/Plotting/Plotter.py, src/sas/qtgui/Plotting/UnitTesting/PlotterTest.py
=> Added context menu item for legend toggle, for quick and regular 1D

src/sas/qtgui/Perspectives/Fitting/SmearingWidget.py, src/sas/qtgui/Perspectives/Fitting/UI/SmearingWidgetUI.ui
Corrected bad behaviour for dQ data smearing and made interface and behaviour for the different cases equivalent to that of SasView 4.2.2
=> Ess gui 1547 smearing

.travis.yml, src/sas/sascalc/pr/calc.py
=> pr: fix numba type error causing failures on linux

src/sas/qtgui/MainWindow/MainWindow.py, src/sas/qtgui/MainWindow/UI/MainWindowUI.ui, src/sas/qtgui/MainWindow/UnitTesting/MainWindowTest.py
=> Added vertical and horizontal scrollbars to the main canvas. #1543

build_tools/conda_qt5_win_commercial.yml
Creating PR to enable installer build for testing.
=> Trying to enforce MKL versioning

setup.py
Addresses #1467 by specifying command arguments which should not trigger the UI build.
=> Minor improvements to setup.py

build_tools/conda_qt5_min_ubuntu.yml, build_tools/conda_qt5_osx.yml, build_tools/conda_qt5_win.yml, build_tools/conda_qt5_win_commercial.yml
Windows was fine already. On OSX I had to update package locally (due to general issues with setting up enviroment) and osx yml file is updated for consistency.
=> updating sphinx, so it can run with keep-going flag

.travis.yml
=> Updating travis file so CI runs with main branch

build_tools/conda_qt5_win_commercial.yml
Don't merge. Testing the newest packages compatibility
=> WIP. Updated windows yaml file

build_tools/conda_qt5_win_commercial.yml
=> Revert "WIP. Updated windows yaml file"

src/sas/qtgui/Calculators/GenericScatteringCalculator.py
Also, corrected errors on plot close in this calculator. #1681
=> Fixed empty plots for Generic Scattering Calculator. 

src/sas/sascalc/dataloader/readers/anton_paar_saxs_reader.py, src/sas/sascalc/dataloader/readers/cansas_reader.py, src/sas/sascalc/dataloader/readers/cansas_reader_HDF5.py, src/sas/sascalc/dataloader/readers/xml_reader.py, test/sasdataloader/utest_cansas.py
This is a parallel PR to #1679 pointing to the wxPython/master branch. The only differences between the two PRs are py2 specific changes in this branch.
=> wxPython: Dataloader fixes including CanSAS XML Refactor

src/sas/sascalc/dataloader/readers/anton_paar_saxs_reader.py, src/sas/sascalc/dataloader/readers/cansas_reader.py, src/sas/sascalc/dataloader/readers/cansas_reader_HDF5.py, src/sas/sascalc/dataloader/readers/xml_reader.py, test/sasdataloader/utest_cansas.py
A few fixes and improvements to the data loader system.
- Refactor of the CanSAS XML reader for stylistic reasons resulting in a ~20% increase in loading times (closes #1303)
- Fix the PDH reader bug (fixes #1671)
- Fix a bug in the NXcanSAS reader related to loading Q resolution (not ticketed)
This is the 6th PR separating #1559.
=> ESS_GUI: Dataloader fixes including CanSAS XML Refactor

src/sas/qtgui/Perspectives/Inversion/InversionPerspective.py, src/sas/qtgui/Plotting/Plottables.py, src/sas/qtgui/Plotting/Plotter.py
Fixes #1725.
To test, use the P(R) calculator with test data and see the horizontal line at y=0 on the P(R) plot.
=> Re #1725 Add horizontal axis

src/sas/qtgui/MainWindow/GuiManager.py, src/sas/qtgui/Perspectives/Inversion/InversionLogic.py
A few instances of logger.log are not used properly. This changes those instances to info or warning instead.
=> logger.log -> logger.<warning|info>

src/sas/qtgui/Perspectives/Invariant/InvariantPerspective.py, src/sas/qtgui/Perspectives/Invariant/UI/TabbedInvariantUI.ui, src/sas/qtgui/Perspectives/Invariant/UnitTesting/InvariantPerspectiveTest.py, src/sas/sascalc/invariant/invariant.py
This PR allows a user to change the extrapolation Q limits in the invariant perspective.
fixes #1609 
This is the 5th (and likely final) PR in the invariant chain: This -> #1717 -> #1716 -> #1715 -> #1709
=> Invariant: Allow user to change extrapolated Q limits

test/sasinvariant/utest_data_handling.py
This fixes the failing invariant test caught by github actions.
=> Fix failing invariant test

src/sas/qtgui/Plotting/PlotProperties.py, src/sas/qtgui/Plotting/PlotUtilities.py, src/sas/qtgui/Plotting/Plotter.py, src/sas/qtgui/Plotting/PlotterBase.py, src/sas/qtgui/Plotting/UnitTesting/PlotterTest.py
Preserving label and custom plot settings from being reset every time fit or comput has been executed.
A lot of GUI tests has been failing but mostly due to slicer changes
=> Ticket 1616

src/sas/qtgui/Plotting/SlicerModel.py, src/sas/qtgui/Plotting/Slicers/BoxSlicer.py
Currently used for `fold`.
Separate commit to the number of points validator fix, both need to be merged.
=> Slicer editor with checkbox

src/sas/qtgui/MainWindow/DataExplorer.py, src/sas/qtgui/MainWindow/GuiManager.py, src/sas/qtgui/Perspectives/Inversion/InversionPerspective.py, src/sas/qtgui/Plotting/Plotter.py, src/sas/qtgui/Plotting/PlotterBase.py, src/sas/qtgui/Plotting/QRangeSlider.py
This corrects issues resulting in errors thrown when data is deleted or new projects are loaded noted by @smk78 in #1772 points [6](https://github.com/SasView/sasview/issues/1772#issuecomment-768257509) and [13](https://github.com/SasView/sasview/issues/1772#issuecomment-768422908) and by @RichardHeenan in multiple comments of #1689.
=> 5.0.4: Fix errors on data deletion and project load

docs/sphinx-docs/source/user/RELEASE.rst
Release notes for 5.0.4 release update
=> Release notes updated

.github/workflows/docs.yml, .github/workflows/installers.yml, docs/sphinx-docs/build_sphinx.py, docs/sphinx-docs/source/conf.py, installers/sasview.py, installers/sasview.spec, src/sas/qtgui/Calculators/DataOperationUtilityPanel.py, src/sas/qtgui/Perspectives/Fitting/FittingPerspective.py, src/sas/sascalc/fit/Loader.py
This is a first attempt at building an installer for windows using GitHub actions. 
The installer that has been generated is available for download from the [summary of the action](https://github.com/llimeht/sasview/actions/runs/490201987). The artifact is called SasView-Installer-{OS}-{PYVER}-{GIT_HASH} (e.g. SasView-Installer-windows-latest-3.8-bbd5cf8edd62cb978e9970ae16d4c9df8d717832) and is a zip file containing the setupSasView.exe installer. (A build triggered by making a release on GitHub should have a nicer artifact name!)
I've only got as far making this build pass, not actually testing that the installer works. Testers needed!
Comments, suggestions and testing most welcome.
(This is Work-In-Progress and not ready to be merged just yet)
=> Build installer for windows using GitHub actions

src/sas/qtgui/MainWindow/DataExplorer.py, src/sas/qtgui/Utilities/ImageViewer.py
Set the correct 2D dataset name.
Avoid querying non-existing attributes.
Addresses #1870
=> Image Viewer bug fix

src/sas/qtgui/Perspectives/Fitting/FittingOptions.py
Added a check for bumps-returned optimizer parameters against available UI fields.
Fixes #1867
=> Optimizer parameters checked against UI fields #1867

src/sas/sascalc/dataloader/readers/cansas_reader.py, src/sas/sascalc/file_converter/nxcansas_writer.py
This fixes two syntax issues in data import/export files, as noted by @pkienzle. There is no associated ticket for this.
=> Data import/export syntax fixes

src/sas/qtgui/MainWindow/GuiManager.py, src/sas/qtgui/MainWindow/MainWindow.py
Attempting to solve issue #1861
=> #1861, adding the SasView version number

src/sas/qtgui/Utilities/AddMultEditor.py, src/sas/qtgui/Utilities/UI/AddMultEditorUI.ui
Added `@` to the list of operators and pretty-fied the label on the widget.
=> Improved add/multiply editor

.github/workflows/installers.yml, installers/sasview.spec
Added dependency on missing modules: `uncertainties`, `debugpy` and `xmlrpc` required for python console
=> python console fix

.github/workflows/release.yml
Not really possible to test until we create a tag. It shouldn't affect running installers builds.
=> Fixing syntax in release.yml

src/sas/sascalc/calculator/sas_gen.py, src/sas/sascalc/pr/num_term.py
This PR improves the data load routine that is used to read omf, and pdb files in the general scattering calculator.
=> File loader enhancement of the General Scattering Calculator

docs/sphinx-docs/source/user/RELEASE.rst, src/sas/qtgui/Perspectives/Fitting/media/fitting.rst, src/sas/qtgui/Perspectives/Fitting/media/fitting_help.rst
This PR is one of two addressing https://github.com/SasView/sasview/issues/1708. The other being https://github.com/SasView/sasmodels/pull/487.
A retrospective comment has been added under 'New in 5.0.4' to RELEASE.rst.
Mention also needs to be made somewhere in the SasView Help docs.
=> Doc Update: P Scaling

src/sas/qtgui/Perspectives/Invariant/InvariantPerspective.py, src/sas/qtgui/Perspectives/Invariant/UnitTesting/InvariantPerspectiveTest.py, src/sas/qtgui/Perspectives/Invariant/media/invariant_help.rst
Removes 3x upper limit on invariant high Q extrapolation plot, and replaces with user defined upper q limit.
Fixes #1749 (High Q Part)
=> Fixes to invariant plot high q extrapolation

installers/installer.iss
=> Increment the installation directory number to 5.0.5

src/sas/qtgui/Perspectives/Fitting/OptionsWidget.py, src/sas/qtgui/Perspectives/Fitting/UnitTesting/FittingWidgetTest.py, src/sas/qtgui/Plotting/Plotter.py, src/sas/qtgui/Plotting/PlotterBase.py, src/sas/qtgui/Plotting/SetGraphRange.py, src/sas/qtgui/Plotting/UnitTesting/PlotterTest.py
This fixes the issue related to resetting the Q-range that was introduced in v5.0.4. Unit tests were added to the `fittingSuite` of `GUITests.py` to ensure the values are reset properly.
Fixes #1814
=> 1814: Q-range reset

docs/sphinx-docs/source/user/RELEASE.rst
This should be the final merge needed prior to the release.
=> Finalize release notes for Release 5.0.5

.github/ISSUE_TEMPLATE/feature_request.md
=> Added feature request label

src/sas/qtgui/Perspectives/Corfunc/UI/SaveExtrapolated.ui, src/sas/qtgui/Perspectives/Corfunc/saveextrapolated.py
@smk78 requests for export file changes
=> 2089 changes to save extrapolation

build_tools/release_automation.py
Adding Nicolas and Lucas to the developers list. We can also add more contributors.
=> Updating developers list for zenodo

src/sas/qtgui/MainWindow/DataExplorer.py
Changed the delete message box in line with the discussion on issue #2049
=> Reworded delete message boxes

src/sas/qtgui/MainWindow/GuiManager.py, src/sas/qtgui/Perspectives/Corfunc/CorfuncPerspective.py, src/sas/qtgui/Perspectives/Corfunc/UI/CorfuncPanel.ui, src/sas/qtgui/Perspectives/Corfunc/corefuncutil.py, src/sas/sascalc/corfunc/corfunc_calculator.py, test/corfunc/utest_corfunc.py
Soft block thickness now present in corfunc. @smk78 to verify it does the right thing.
=> 2108 display average soft block thickness in corfunc

src/sas/qtgui/Utilities/Reports/reportdata.py
=> NamedTuple to @dataclass

src/sas/qtgui/Perspectives/Corfunc/CorfuncPerspective.py
This addresses issue #2105 - its currently a minimal amount of user feedback, the background of the background box changes to yellow - is it sufficient @smk78 ?
=> Yellow background to box for non-negative values

src/sas/qtgui/Perspectives/Corfunc/QSpaceCanvas.py
I've changed the appearance, though there is still the question of how plots are to work in general, and how corfunc plots should work (#2134)
=> Changed appearance of Corfunc q space

src/sas/qtgui/Perspectives/Corfunc/CorfuncPerspective.py
=> 2137 change file format for save transformed in corfunc

src/sas/sascalc/pr/p_invertor.py
Fix for #2176  - can the first person to check it please merge it too!
=> URGENT: Fixed breaking bug in pr_inversion

src/sas/system/env.py
Back to previous functionality
=> Fixed issue with default CL setting conflicts

src/sas/qtgui/MainWindow/GuiManager.py, src/sas/qtgui/MainWindow/MainWindow.py
The window now gracefully maximizes allowing the fitting perspective to be properly displayed with all the buttons visible.
=> Force main window to maximize #2272

src/sas/qtgui/MainWindow/MainWindow.py
Based on @llimeht suggestion, implemented a simple qt loop timer so ctrl-c events are easier to catch.
=> Added a trick to catch ctrl-c quicker.

src/sas/system/log.py
File path error was causing log.ini not found error
=> Fixed file path for log.ini

src/sas/system/log.ini
Disabled the Converting from 5 to 7 etc messages via log
=> Removed debug messages for h5py

src/sas/qtgui/Plotting/Plotter.py
Fixes #2361 after changes in 74358e2de07ea9e7175f8021e9b3547d13a06ea2
Testing description in the issue
=> Fix plot legend not updating on custom change. #2361

src/sas/qtgui/MainWindow/DataExplorer.py
This addresses #2118 - incorrectly populated Graph combobox for theory plots.
=> DIfferentiate which combobox to put the graphs in.

src/sas/system/config/config_meta.py
Quick fix to braking change on main from 2328
@krzywon @wpotrzebowski
=> Quick fix for issue with 2328

build_tools/release_automation.py
Updating zenodo record in release automation script
=> [RELEASE 5.0.6] zenodo record update

docs/sphinx-docs/source/user/RELEASE.rst
=> Final tweak to release notes

installers/installer.iss
This updates the version and copyright date in installer.iss for v5.0.6.
=> [v5.0.6] Update installer.iss with correct version and copyright dates

src/sas/qtgui/MainWindow/DataExplorer.py
Cherrypicked from  #2506 - required fix which should go in regardless of the status of #2506
Fixes asserts on programmatic perspective changes
Locally win10
=> Perspective change fix which should go to 5.0.6

src/sas/qtgui/MainWindow/DataExplorer.py, src/sas/qtgui/Perspectives/Fitting/ViewDelegate.py, src/sas/qtgui/Plotting/ColorMap.py, src/sas/qtgui/Plotting/rangeSlider.py
A few minor fixes required for the Ubuntu version to run from the conda-forge prepared installation.
Fixes:
- errors on perspective switch
- errors in populating parameter table
- errors in functionality of the color map (2D)
Locally on Ubuntu from `conda install -c conda-forge sasview`
=> These fixes are for the Ubuntu conda-forge distribution.

.github/workflows/ci.yml, .github/workflows/nightly-build.yml
Some additional fixes to GH actions as the previous version was failing on nightly build
=> Moving OSX signing to nigthly build (ver 2)

src/sas/qtgui/Perspectives/Fitting/ConstraintWidget.py, src/sas/qtgui/Perspectives/Fitting/FittingWidget.py, src/sas/qtgui/Perspectives/Fitting/MultiConstraint.py
Fixes the problems with the remove/edit constraint options, including the constraints on polydisperse parameters.
Note that the validation of the formula has been disabled, as it is not working properly and this will require much more thought to fix. A separate issue (#2740) has been created for this.
Fixes # 2355
Create a project, define a few constraints (including polydisperse parameters) and play removing and editing them from the right mouse button menu.
=> 2355 edit remove constraints

src/sas/qtgui/MainWindow/DataExplorer.py
Set the visibility flag on result panel properly
Fixes #2776 
Win10 build
=> Close all plots when required

src/sas/qtgui/Perspectives/Fitting/FittingWidget.py, src/sas/qtgui/Perspectives/Fitting/SmearingWidget.py, src/sas/qtgui/Perspectives/Fitting/UI/SmearingWidgetUI.ui, src/sas/sascalc/fit/qsmearing.py
Cherry picking changes form PR #2744 as rebasing onto the 6.0.0 release branch was not an option.
=> 1932 cherry pick

src/sas/system/config/config.py
Cleaned up config so that we don't have unused entries.
Fixes #2895
=> Cleaned unused item from config

src/sas/qtgui/Perspectives/Corfunc/media/corfunc-technical.rst
@smk78 Done. Do you want to check things are still correct?
Fixes #2913
**Installers**
=> 2913 corfunc technical needs attention

build_tools/contributors.tsv
This just copies the build_tools/Contributor.tsv from PR #2883 to a branch off of release_6.0.0 instead of main. This was done by creating a new branch from release_6.0.0 and using the `checkout branch -- file` to copy an existing blob
=> Add contributors list to release 6.0

src/sas/qtgui/MainWindow/Acknowledgements.py, src/sas/qtgui/Perspectives/Inversion/DMaxExplorerWidget.py, src/sas/qtgui/Plotting/AddText.py, src/sas/qtgui/Utilities/About/About.py, src/sas/qtgui/Utilities/FileConverter.py, src/sas/qtgui/Utilities/OrientationViewer/OrientationViewer.py, src/sas/qtgui/Utilities/WhatsNew/WhatsNew.py
I have checked every window (I think) for missing icons and fixed them all.
=> Set missing icons

src/sas/qtgui/Calculators/GenericScatteringCalculator.py
Should fix #2916  - however, my computer is too fast to reproduce the issue with any of the example data. @smk78 - can you check?
=> 2916 gsc plot windows can open hidden - also add GSC plot icon

src/sas/qtgui/Utilities/OrientationViewer/OrientationViewer.py
Adds help button that directs to the orientation help
=> 2905 - Orientation Viewer Tool needs a Help Button & Documentation

src/sas/qtgui/Utilities/GuiUtils.py
There were some issues with variable re-use that caused the wrong units to appear on some of the differently scaled plots. Fixes this.
=> 2990 - Fixed units in scaled plots

src/sas/qtgui/Perspectives/Inversion/InversionPerspective.py
This changes the mechanism for removing data from the P(r) perspective. See code comments for why.
**Installers**
=> Fix to Inversion data removal

src/sas/qtgui/Plotting/PlotterBase.py
Just the little spelling mistake
none
started sasview, worked properly
there should be no other appearances of the method
**Installers**
=> correct little spelling mistake updatePlotHelper

src/sas/qtgui/Perspectives/Fitting/GPUOptions.py, src/sas/sascalc/calculator/sas_gen.py
This fixes two wrinkles found in a couple of issues. The GSC could load invalid files, which then failed to run the computation on those files. The GPU Options window would not change the selected option when the tests were run. Both of these are fixed here.
~~NOTE: If I find a solution to https://github.com/SasView/sasview/issues/2975#issuecomment-2375220706, I will try to get it in here~~ (long-standing issue that won't be fixed in 6.0.0)
(maybe) Fixes #3055 
refs #2975
=> Various 6.0.0 fixes

docs/sphinx-docs/source/user/RELEASE.rst
A final update to the release notes in preparation on the v6.0.0 release.
=> v6.0.0: Final release notes

build_tools/application_metadata/org.sasview.sasview.desktop, build_tools/application_metadata/org.sasview.sasview.metainfo.xml
Some minor fixes to the metadata files. The Flatpak is going to be based on this branch as these fixes were required to pass its review. 
The Flatpak has passed its review with these changes, and the appropriate metadata is displayed on [Flathub](https://flathub.org/apps/org.sasview.sasview).
**Installers**
=> Metadata fixes

src/sas/qtgui/Utilities/ModelEditors/TabbedEditor/TabbedModelEditor.py
A line was supposed to be moved 2 lines down, but the operation was a copy, not a move.
Fixes #3296
Local dev build
**Installers**
=> removed superfluous line

src/sas/qtgui/Perspectives/SizeDistribution/SizeDistributionPerspective.py
- Remove model `dataChanged` connection
- Install an event filter for the background input widgets that should update the data plot. The event filter ensures that the plot is not updated until the user presses Enter.
- Update the background data and plot when the background input widgets are updated programmatically, e.g. after fitting the background.
Fixes #3277 
Tested locally in the dev environment by adding data to the Size Distribution perspective and verifying that the data plot does not get updated until the user presses Enter in one of the background input boxes or changes the state of the checkbox. The plot is not updated if the user deletes the text in the input box. …
=> Wait to update Size Distribution data plot until user presses Enter

src/sas/qtgui/Perspectives/Inversion/InversionPerspective.py, src/sas/qtgui/Perspectives/Inversion/NewInversionWidget.py
Fixed lifetime of the logic component.
Fixes #3318 
Local win10 dev build
- [X ] There is **nothing** that needs documenting
**Installers**
=> 3318 saving project fails

src/sas/qtgui/Utilities/WhatsNew/messages/6.1.0/3.html
=> 3490: MumMag -> MuMag
